CREATE OR ALTER PROCEDURE [dbo].[SP_CURRANCY_MASTER_Select]

@CURR_COUNTRY_CODE int,
@CURR_CODE int,
@CURR_CM_COMP_ID int,
@CURR_NAME varchar(50),
@CURR_SHORT_NAME varchar(50),
@CURR_DESC varchar(50),
@ES_DELETE bit,
@MODIFY bit,
@TYPE VARCHAR(50),
@CURR_RATE float

AS

if @TYPE='CHECKUPDATE'
begin

Select 
CURR_COUNTRY_CODE,
CURR_CODE,
CURR_CM_COMP_ID,
CURR_NAME,
CURR_SHORT_NAME,
CURR_DESC,
ES_DELETE,
CURR_RATE,
MODIFY

from CURRANCY_MASTER

where 
( @CURR_COUNTRY_CODE is null or @CURR_COUNTRY_CODE = CURR_COUNTRY_CODE ) and
( @CURR_CODE is null or @CURR_CODE != CURR_CODE ) and
( @CURR_CM_COMP_ID is null or @CURR_CM_COMP_ID = CURR_CM_COMP_ID ) and
( @CURR_COUNTRY_CODE is null or @CURR_COUNTRY_CODE = CURR_COUNTRY_CODE )and 


--( @CURR_NAME is null or @CURR_NAME = CURR_NAME )and 
( @ES_DELETE is null or @ES_DELETE = ES_DELETE ) and
 @ES_DELETE = ES_DELETE

end
else
begin

Select 
CURR_COUNTRY_CODE,
CURR_CODE,
CURR_CM_COMP_ID,
CURR_NAME,
CURR_SHORT_NAME,
CURR_DESC,
ES_DELETE,
CURR_RATE,
MODIFY

from CURRANCY_MASTER

where

 ( @CURR_COUNTRY_CODE is null or @CURR_COUNTRY_CODE = CURR_COUNTRY_CODE ) and
--( @CURR_CODE is null or @CURR_CODE = CURR_CODE ) and
( @CURR_CM_COMP_ID is null or @CURR_CM_COMP_ID = CURR_CM_COMP_ID ) and
--( @CURR_NAME is null or @CURR_NAME = CURR_NAME )and
( @CURR_COUNTRY_CODE is null or @CURR_COUNTRY_CODE = CURR_COUNTRY_CODE )and 

--( @CURR_SHORT_NAME is null or @CURR_SHORT_NAME = CURR_SHORT_NAME ) and
--( @CURR_DESC is null or @CURR_DESC = CURR_DESC ) and
( @ES_DELETE is null or @ES_DELETE = ES_DELETE ) and
 @ES_DELETE = ES_DELETE

end