CREATE OR ALTER PROCEDURE [dbo].[SP_CITY_MASTER_INSERT]

@CITY_CM_COMP_ID int,
@CITY_COUNTRY_CODE int,
@CITY_SM_CODE int,
@CITY_NAME varchar(50)

AS

Insert into CITY_MASTER
(
CITY_CM_COMP_ID,
CITY_COUNTRY_CODE,
CITY_SM_CODE,
CITY_NAME
)
values
(
@CITY_CM_COMP_ID,
@CITY_COUNTRY_CODE,
@CITY_SM_CODE,
@CITY_NAME
)