CREATE OR ALTER PROCEDURE [dbo].[SP_CURRANCY_MASTER_INSERT]
@CURR_COUNTRY_CODE int,
@CURR_CM_COMP_ID int,
@CURR_NAME varchar(50),
@CURR_SHORT_NAME varchar(50),
@CURR_DESC varchar(50),
@CURR_RATE float


AS

Insert into CURRANCY_MASTER
(
CURR_COUNTRY_CODE,
CURR_CM_COMP_ID,
CURR_NAME,
CURR_SHORT_NAME,
CURR_DESC,
CURR_RATE
)
values
(
@CURR_COUNTRY_CODE,
@CURR_CM_COMP_ID,
@CURR_NAME,
@CURR_SHORT_NAME,
@CURR_DESC,
@CURR_RATE
)