CREATE OR ALTER PROCEDURE [dbo].[SP_COUNTRY_MASTER_Update]

@COUNTRY_CODE    int,
@COUNTRY_CM_COMP_ID    int,
@COUNTRY_NAME    varchar(50),
@ES_DELETE    bit,
@MODIFY bit

AS

Update COUNTRY_MASTER

Set
	
	COUNTRY_CM_COMP_ID = @COUNTRY_CM_COMP_ID,
	COUNTRY_NAME = @COUNTRY_NAME,
	ES_DELETE = @ES_DELETE,
	MODIFY = @MODIFY 
Where

COUNTRY_CODE = @COUNTRY_CODE