CREATE OR ALTER PROCEDURE [dbo].[SP_CITY_MASTER_UPDATE]

@CITY_CODE    int,
@CITY_CM_COMP_ID    int,
@CITY_COUNTRY_CODE int,
@CITY_SM_CODE int,
@CITY_NAME varchar(50)

AS

Update CITY_MASTER

Set
	
	CITY_CM_COMP_ID = @CITY_CM_COMP_ID,
	CITY_COUNTRY_CODE=@CITY_COUNTRY_CODE,
	CITY_SM_CODE=@CITY_SM_CODE,
	CITY_NAME = @CITY_NAME
	 
Where

CITY_CODE = @CITY_CODE