CREATE OR ALTER PROCEDURE [dbo].[SP_COUNTORY_MASTER_Select]


@COUNTRY_CODE int,
@COUNTRY_CM_COMP_ID int,
@COUNTRY_NAME varchar(50),
@ES_DELETE bit,
@MODIFY bit,
@TYPE VARCHAR(50)

AS
if @TYPE='CHECKUPDATE'
begin
Select 

COUNTRY_CODE,
COUNTRY_CM_COMP_ID,
COUNTRY_NAME,
ES_DELETE,
MODIFY

from COUNTRY_MASTER

where 
( @COUNTRY_CODE is null or @COUNTRY_CODE != COUNTRY_CODE ) and
( @COUNTRY_CM_COMP_ID is null or @COUNTRY_CM_COMP_ID = COUNTRY_CM_COMP_ID ) and
( @COUNTRY_NAME is null or @COUNTRY_NAME = COUNTRY_NAME ) and
( @ES_DELETE is null or @ES_DELETE = ES_DELETE ) and
 @ES_DELETE = ES_DELETE
end
else
begin
Select 

COUNTRY_CODE,
COUNTRY_CM_COMP_ID,
COUNTRY_NAME,
ES_DELETE,
MODIFY

from COUNTRY_MASTER

where 
( @COUNTRY_CODE is null or @COUNTRY_CODE = COUNTRY_CODE ) and
( @COUNTRY_CM_COMP_ID is null or @COUNTRY_CM_COMP_ID = COUNTRY_CM_COMP_ID ) and
( @COUNTRY_NAME is null or @COUNTRY_NAME = COUNTRY_NAME ) and
( @ES_DELETE is null or @ES_DELETE = ES_DELETE ) and
 @ES_DELETE = ES_DELETE order by COUNTRY_NAME
end