CREATE OR ALTER PROCEDURE [dbo].[SP_CURRANCY_MASTER_Update]

@CURR_COUNTRY_CODE int,
@CURR_CODE   int,
@CURR_CM_COMP_ID    int,
@CURR_NAME    varchar(50),
@CURR_SHORT_NAME Varchar(50),
@CURR_DESC Varchar(50),
@CURR_RATE float

AS

Update CURRANCY_MASTER

Set
	CURR_COUNTRY_CODE=@CURR_COUNTRY_CODE,
	CURR_CM_COMP_ID = @CURR_CM_COMP_ID,
	CURR_NAME = @CURR_NAME,
	CURR_SHORT_NAME = @CURR_SHORT_NAME,
	 CURR_DESC = @CURR_DESC,
	 CURR_RATE=@CURR_RATE
	
Where

CURR_CODE = @CURR_CODE