CREATE OR ALTER PROCEDURE [dbo].[SP_EXCISE_TARIFF_MASTER_Update]

@E_CODE int,
@E_CM_COMP_ID int,
@E_TARIFF_NO varchar(50),
@E_COMMODITY varchar(50),
@E_BASIC Float,
@E_SPECIAL Float,
@E_EDU_CESS Float,
@E_H_EDU float,

@E_TALLY_BASIC int,
@E_TALLY_SPECIAL int,
@E_TALLY_EDU int,
@E_TALLY_H_EDU int,

@ES_DELETE bit,
@MODIFY bit

AS

Update EXCISE_TARIFF_MASTER

Set
	
	 E_CM_COMP_ID=@E_CM_COMP_ID, 
	 E_TARIFF_NO=@E_TARIFF_NO,
	 E_COMMODITY=@E_COMMODITY, 
	 E_BASIC=@E_BASIC, 
	 E_SPECIAL=@E_SPECIAL, 
	 E_EDU_CESS=@E_EDU_CESS,
	 E_H_EDU=@E_H_EDU,
	 
	 E_TALLY_BASIC=@E_TALLY_BASIC,
	 E_TALLY_SPECIAL=@E_TALLY_SPECIAL,
     E_TALLY_EDU=@E_TALLY_EDU,
     E_TALLY_H_EDU=@E_TALLY_H_EDU,
	 
	 
	 ES_DELETE = @ES_DELETE,
	 MODIFY = @MODIFY 
Where

E_CODE = @E_CODE