CREATE OR ALTER PROCEDURE [dbo].[SP_EXCISE_TARIFF_MASTER_Insert]


@E_CM_COMP_ID int,
@E_TARIFF_NO varchar(50),
@E_COMMODITY varchar(50),
@E_BASIC Float,
@E_SPECIAL Float,
@E_EDU_CESS Float,
@E_H_EDU float,

@E_TALLY_BASIC int,
@E_TALLY_SPECIAL int,
@E_TALLY_EDU int,
@E_TALLY_H_EDU int,

@E_TALLY_GST_EXCISE bit,
@ES_DELETE bit,
@MODIFY bit

AS

Insert into EXCISE_TARIFF_MASTER
(
E_CM_COMP_ID, 
E_TARIFF_NO, 
E_COMMODITY,
 E_BASIC, 
 E_SPECIAL,
  E_EDU_CESS,
  E_H_EDU, 
  
  E_TALLY_BASIC,
E_TALLY_SPECIAL,
E_TALLY_EDU,
E_TALLY_H_EDU,
  
  E_TALLY_GST_EXCISE,
  ES_DELETE,
   MODIFY
)
values
(
@E_CM_COMP_ID,
@E_TARIFF_NO,
@E_COMMODITY,
@E_BASIC,
@E_SPECIAL,
@E_EDU_CESS,
@E_H_EDU,

@E_TALLY_BASIC,
@E_TALLY_SPECIAL,
@E_TALLY_EDU,
@E_TALLY_H_EDU,

@E_TALLY_GST_EXCISE,
@ES_DELETE,
@MODIFY
)