CREATE OR ALTER PROCEDURE [dbo].[SP_GetUserRightsDetails]

AS
BEGIN

select UR_UM_CODE,UM_USERNAME
from USER_MASTER,USER_RIGHT,SCREEN_MASTER
where UM_CODE=UR_UM_CODE and UR_SM_CODE=SM_CODE 
and UR_IS_DELETE='0' and ES_DELETE='0'
group by UR_UM_CODE,UM_USERNAME
	
END