CREATE OR ALTER PROCEDURE [dbo].[SP_GetUserRightInfo]
@UR_UM_CODE	int
AS
BEGIN

select UR_UM_CODE,UR_SM_CODE,SM_NAME,UR_RIGHTS from USER_RIGHT,SCREEN_MASTER
where UR_UM_CODE=@UR_UM_CODE and 
SM_CODE=UR_SM_CODE

END