CREATE OR ALTER PROCEDURE [dbo].[SP_INSERT_InspectionPDIDetail]
@INSPDI_INSM_CODE int=0,
@INSPDI_PARAMETERS varchar(50)='',
@INSPDI_SPECIFTION varchar(50)='',
@INSPDI_INSPECTION varchar(50)='',
@INSPDI_OBSR1 varchar(50)='',
@INSPDI_OBSR2 varchar(50)='',
@INSPDI_OBSR3 varchar(50)='',
@INSPDI_OBSR4 varchar(50)='',
@INSPDI_OBSR5 varchar(50)='',
@INSPDI_DSPOSITION varchar(50)='',
@INSPDI_REMARK varchar(250)='',
@INSPDI_I_CODE int=0

AS
BEGIN
INSERT INTO INSPECTION_PDI_DETAIL(INSPDI_INSM_CODE,
            INSPDI_PARAMETERS,
            INSPDI_SPECIFTION,
INSPDI_INSPECTION,
INSPDI_OBSR1,
INSPDI_OBSR2,
INSPDI_OBSR3,
INSPDI_OBSR4,
INSPDI_OBSR5,
INSPDI_DSPOSITION,
INSPDI_REMARK,
INSPDI_I_CODE)
            
    VALUES(@INSPDI_INSM_CODE,    
@INSPDI_PARAMETERS,
@INSPDI_SPECIFTION,
@INSPDI_INSPECTION,
@INSPDI_OBSR1,
@INSPDI_OBSR2,
@INSPDI_OBSR3,
@INSPDI_OBSR4,
@INSPDI_OBSR5,
@INSPDI_DSPOSITION,
@INSPDI_REMARK,
@INSPDI_I_CODE
            )
END