CREATE OR ALTER PROCEDURE [dbo].[SP_ITEM_CATEGORY_MASTER_Insert]


@I_CAT_CM_COMP_ID int,
@I_CAT_NAME varchar(50),
@ES_DELETE bit,
@MODIFY bit,
@I_CAT_SHORTCLOSE bit
AS

Insert into ITEM_CATEGORY_MASTER
(
I_CAT_CM_COMP_ID,
I_CAT_NAME,
ES_DELETE,
MODIFY,I_CAT_SHORTCLOSE
)
values
(
@I_CAT_CM_COMP_ID,
@I_CAT_NAME,
@ES_DELETE,
@MODIFY,@I_CAT_SHORTCLOSE

)