CREATE OR ALTER PROCEDURE [dbo].[SP_INSERT_InspectionDetail]
@INSD_INSM_CODE int,
@INSD_I_CODE int,
@INSD_RM_CODE varchar(150),
@INSD_REJ_QTY float

AS
BEGIN
INSERT INTO INSPECTION_S_DETAIL(INSD_INSM_CODE,
			INSD_I_CODE,
			INSD_RM_CODE,
			INSD_REJ_QTY
			)
			
     VALUES(@INSD_INSM_CODE,
			 @INSD_I_CODE,
			 @INSD_RM_CODE,
			 @INSD_REJ_QTY
			)
END