CREATE OR ALTER PROCEDURE [dbo].[SP_ITEM_CATEGORY_MASTER_Update]


@I_CAT_CODE    int,
@I_CAT_CM_COMP_ID    int,
@I_CAT_NAME    varchar(50),
@ES_DELETE    bit,
@MODIFY bit,
@I_CAT_SHORTCLOSE bit
AS

Update ITEM_CATEGORY_MASTER

Set
	
	I_CAT_CM_COMP_ID = @I_CAT_CM_COMP_ID,
	I_CAT_NAME = @I_CAT_NAME,
	ES_DELETE = @ES_DELETE,
	 MODIFY = @MODIFY,
	I_CAT_SHORTCLOSE=@I_CAT_SHORTCLOSE
Where

I_CAT_CODE = @I_CAT_CODE