CREATE OR ALTER PROCEDURE [dbo].[SP_INSERT_BILLPASSING_MASTER] 
(
		@PROCESS nvarchar(20)='',
		@BPM_CODE int,
		@BPM_CM_CODE int,
		@BPM_NO numeric,
		@BPM_DATE datetime,
		@BPM_P_CODE int,
		--@BPM_IWM_CODE int,
		@BPM_INV_NO varchar(50),
		@BPM_INV_DATE datetime,
		@BPM_BILL_PASS_BY varchar(50),
		@BPM_BASIC_AMT float,
		@BPM_DISCOUNT_AMT float,
		@BPM_PACKING_AMT float,	
		@BPM_ACCESS_AMT float,	
		@BPM_EXCIES_AMT float,
		@BPM_ECESS_AMT float,
		@BPM_HECESS_AMT float,
		@BPM_EXCPER float,
		@BPM_EXCEDCESS_PER float,
		@BPM_EXCHIEDU_PER float,
		@BPM_TAXABLE_AMT float,		
		@BPM_TAX_AMT float,
		@BPM_TAX_PER float,	
		@BPM_TAX_CODE int,
		@BPM_OTHER_AMT float,
		@BPM_ADD_DUTY float,
		@BPM_FREIGHT float,
		@BPM_INSURRANCE float,
		@BPM_TRANSPORT float,
		@BPM_OCTRO_AMT float,
		@BPM_ROUND_OFF float,		
		@BPM_G_AMT float,	
		@BPM_EX_TYPE varchar(50),
		@BPM_TYPE varchar(50)='',
		@BPM_IS_SERVICEIN INT,
		@PK_CODE numeric(18,0) Output,
		@ERROR varchar(max) Output
		
)
AS
--For Save
	BEGIN
	    BEGIN TRY 
			IF @PROCESS='Insert'	
				BEGIN-------Insert
							IF NOT EXISTS(SELECT BPM_NO FROM BILL_PASSING_MASTER WHERE BPM_NO=@BPM_NO AND BPM_TYPE=@BPM_TYPE and ES_DELETE=0 and BPM_CM_CODE=@BPM_CM_CODE)
								BEGIN---Check  Area No
										Insert into BILL_PASSING_MASTER(BPM_CM_CODE,BPM_NO,
BPM_DATE,BPM_P_CODE,BPM_INV_NO,BPM_INV_DATE,BPM_BILL_PASS_BY,BPM_BASIC_AMT,BPM_DISCOUNT_AMT,
BPM_PACKING_AMT,BPM_ACCESS_AMT,BPM_EXCIES_AMT,BPM_ECESS_AMT,BPM_HECESS_AMT,BPM_EXCPER,BPM_EXCEDCESS_PER,BPM_EXCHIEDU_PER,BPM_TAXABLE_AMT,BPM_TAX_AMT,BPM_TAX_PER,BPM_TAX_CODE,BPM_OTHER_AMT,BPM_ADD_DUTY,BPM_FREIGHT,BPM_INSURRANCE,BPM_TRANSPORT,BPM_ROUND_OFF,BPM_OCTRO_AMT,BPM_G_AMT,BPM_EX_TYPE,BPM_TYPE,BPM_IS_SERVICEIN
)
values
(
@BPM_CM_CODE,@BPM_NO,@BPM_DATE,@BPM_P_CODE,@BPM_INV_NO,@BPM_INV_DATE,@BPM_BILL_PASS_BY,
@BPM_BASIC_AMT,@BPM_DISCOUNT_AMT,@BPM_PACKING_AMT,@BPM_ACCESS_AMT,@BPM_EXCIES_AMT,@BPM_ECESS_AMT,@BPM_HECESS_AMT,
@BPM_EXCPER,@BPM_EXCEDCESS_PER,@BPM_EXCHIEDU_PER,@BPM_TAXABLE_AMT,@BPM_TAX_AMT,@BPM_TAX_PER,@BPM_TAX_CODE,@BPM_OTHER_AMT,@BPM_ADD_DUTY,@BPM_FREIGHT,@BPM_INSURRANCE,@BPM_TRANSPORT,@BPM_ROUND_OFF,@BPM_OCTRO_AMT,@BPM_G_AMT,@BPM_EX_TYPE,@BPM_TYPE,@BPM_IS_SERVICEIN)
										
										IF (@@ROWCOUNT>0)     
										 BEGIN-----------1 
											SET @PK_CODE=SCOPE_IDENTITY()
											SET @ERROR='Record Successfully Saved'																
									     END-------------1	
						          END------Check Description					 				
		                 	ELSE 
				                 BEGIN---isexist
						     	  SET @PK_CODE=0
							      SET @ERROR='Bill No. Already Exist'	
				            END----isexist
		     END
		ELSE IF @PROCESS='Update'
			  BEGIN
				  IF NOT EXISTS(SELECT BPM_NO FROM BILL_PASSING_MASTER WHERE BPM_CODE<>@BPM_CODE and BPM_NO=@BPM_NO and ES_DELETE=0 AND BPM_TYPE=@BPM_TYPE and BPM_CM_CODE=@BPM_CM_CODE)
					BEGIN----1
						     Update BILL_PASSING_MASTER Set 
	BPM_CM_CODE=@BPM_CM_CODE,BPM_NO=@BPM_NO,BPM_DATE=@BPM_DATE,BPM_P_CODE=@BPM_P_CODE,BPM_INV_NO=@BPM_INV_NO,
	BPM_INV_DATE=@BPM_INV_DATE,BPM_BILL_PASS_BY=@BPM_BILL_PASS_BY,
BPM_BASIC_AMT=@BPM_BASIC_AMT,BPM_DISCOUNT_AMT=@BPM_DISCOUNT_AMT,BPM_PACKING_AMT=@BPM_PACKING_AMT,
BPM_ACCESS_AMT=@BPM_ACCESS_AMT,BPM_EXCIES_AMT=@BPM_EXCIES_AMT,BPM_ECESS_AMT=@BPM_ECESS_AMT,BPM_HECESS_AMT=@BPM_HECESS_AMT,
BPM_EXCPER=@BPM_EXCPER,BPM_EXCEDCESS_PER=@BPM_EXCEDCESS_PER,BPM_EXCHIEDU_PER=@BPM_EXCHIEDU_PER,
BPM_TAXABLE_AMT=@BPM_TAXABLE_AMT,BPM_TAX_AMT=@BPM_TAX_AMT,BPM_TAX_PER=@BPM_TAX_PER,BPM_TAX_CODE=@BPM_TAX_CODE,BPM_OTHER_AMT=@BPM_OTHER_AMT,
BPM_ADD_DUTY=@BPM_ADD_DUTY,BPM_FREIGHT=@BPM_FREIGHT,BPM_INSURRANCE=@BPM_INSURRANCE,BPM_TRANSPORT=@BPM_TRANSPORT,
BPM_ROUND_OFF=@BPM_ROUND_OFF,BPM_OCTRO_AMT=@BPM_OCTRO_AMT,BPM_G_AMT=@BPM_G_AMT,BPM_EX_TYPE=@BPM_EX_TYPE,BPM_IS_SERVICEIN=@BPM_IS_SERVICEIN
	                        where BPM_NO=@BPM_NO
								 IF (@@ROWCOUNT>0)     
									  BEGIN-----------1 
										SET @PK_CODE=@BPM_CODE
										SET @ERROR='Record Successfully Updated'																
									 END-------------1	
						
					END				
					ELSE 
						BEGIN----Area Name Already Exist
							SET @PK_CODE=0
							SET @ERROR='Bill No Already Exist'	
						END----Area Name Already Exist
		     END----1
		
		

end TRY 
		begin catch
			SET @PK_CODE=0
			SET  @ERROR= ERROR_MESSAGE();
		end catch    
END