CREATE OR ALTER PROCEDURE SP_ITEM_UNIT_MASTER_Update


@I_UOM_CODE    int,
@I_UOM_CM_COMP_ID    int,
@I_UOM_NAME    varchar(50),
@I_UOM_DESC    varchar(50),
@ES_DELETE    bit,
@MODIFY bit
AS

Update ITEM_UNIT_MASTER

Set
	
	I_UOM_CM_COMP_ID = @I_UOM_CM_COMP_ID,
	I_UOM_NAME = @I_UOM_NAME,
	I_UOM_DESC = @I_UOM_DESC,
	ES_DELETE = @ES_DELETE,
	 MODIFY = @MODIFY
Where

I_UOM_CODE = @I_UOM_CODE