CREATE OR ALTER PROCEDURE [dbo].[SP_PROCESS_MASTER_Select]


@PROCESS_CODE int,
@PROCESS_CM_COMP_ID int,
@PROCESS_NAME varchar(50),
@ES_DELETE bit,
@MODIFY bit,
@TYPE VARCHAR(50)

AS
if @TYPE='CHECKUPDATE'
begin
Select 

PROCESS_CODE,
PROCESS_CM_COMP_ID,
PROCESS_NAME,
ES_DELETE,
MODIFY

from PROCESS_MASTER

where 
( @PROCESS_CODE is null or @PROCESS_CODE != PROCESS_CODE ) and
( @PROCESS_CM_COMP_ID is null or @PROCESS_CM_COMP_ID = PROCESS_CM_COMP_ID ) and
( @PROCESS_NAME is null or @PROCESS_NAME = PROCESS_NAME ) and
( @ES_DELETE is null or @ES_DELETE = ES_DELETE ) and
 @ES_DELETE = ES_DELETE
end
else
begin
Select 

PROCESS_CODE,
PROCESS_CM_COMP_ID,
PROCESS_NAME,
ES_DELETE,
MODIFY

from PROCESS_MASTER

where 
( @PROCESS_CODE is null or @PROCESS_CODE = PROCESS_CODE ) and
( @PROCESS_CM_COMP_ID is null or @PROCESS_CM_COMP_ID = PROCESS_CM_COMP_ID ) and
( @PROCESS_NAME is null or @PROCESS_NAME = PROCESS_NAME ) and
( @ES_DELETE is null or @ES_DELETE = ES_DELETE ) and
 @ES_DELETE = ES_DELETE order by PROCESS_NAME
end