CREATE OR ALTER PROCEDURE [dbo].[SP_Process_MASTER_Update]

@PROCESS_CODE    int,
@PROCESS_CM_COMP_ID    int,
@PROCESS_NAME    varchar(50),
@ES_DELETE    bit,
@MODIFY bit

AS

Update PROCESS_MASTER

Set
	
	PROCESS_CM_COMP_ID = @PROCESS_CM_COMP_ID,
	PROCESS_NAME = @PROCESS_NAME,
	ES_DELETE = @ES_DELETE,
	MODIFY = @MODIFY 
Where

PROCESS_CODE = @PROCESS_CODE