CREATE OR ALTER PROCEDURE [dbo].[SP_RoleExists]
    @RoleName NVARCHAR(100)
AS
BEGIN
    SET NOCOUNT ON;

    SELECT CASE WHEN EXISTS (SELECT 1 FROM ROLES WHERE RoleName = @RoleName) THEN 1 ELSE 0 END AS RoleExists;
END