CREATE OR ALTER PROCEDURE [dbo].[SP_STATE_MASTER_INSERT]

@SM_CM_COMP_ID int,
@SM_NAME varchar(50),
@SM_COUNTRY_CODE int,
@SM_STATE_CODE INT=0
AS

Insert into STATE_MASTER
(
SM_CM_COMP_ID,
SM_NAME,
SM_COUNTRY_CODE,
SM_STATE_CODE
)
values
(
@SM_CM_COMP_ID,
@SM_NAME,
@SM_COUNTRY_CODE,
@SM_STATE_CODE
)