CREATE OR ALTER PROCEDURE SP_SECTOR_MASTER_Update


@SCT_CODE    int,
@SCT_CM_COMP_ID    int,
@SCT_DESC    varchar(50),
@ES_DELETE    bit,
@MODIFY bit

AS

Update SECTOR_MASTER

Set
	
	SCT_CM_COMP_ID = @SCT_CM_COMP_ID,
	SCT_DESC = @SCT_DESC,
	ES_DELETE = @ES_DELETE,
	MODIFY = @MODIFY 
Where

SCT_CODE = @SCT_CODE