CREATE OR ALTER PROCEDURE [dbo].[SP_SetItemCategoryActiveStatus]
    @I_CAT_CODE INT,
    @ES_DELETE BIT
AS
BEGIN
    SET NOCOUNT OFF;
    
    UPDATE ITEM_CATEGORY_MASTER
    SET ES_DELETE = @ES_DELETE
    WHERE I_CAT_CODE = @I_CAT_CODE;
    
    SELECT @@ROWCOUNT AS AffectedRows;
END