CREATE OR ALTER PROCEDURE [dbo].[SP_STATE_MASTER_UPDATE]

@SM_CODE    int,
@SM_CM_COMP_ID    int,
@SM_NAME    varchar(50),
@SM_COUNTRY_CODE int,
@SM_STATE_CODE varchar(50)=''
AS

Update STATE_MASTER

Set
	
	SM_CM_COMP_ID = @SM_CM_COMP_ID,
	SM_NAME = @SM_NAME,
	SM_COUNTRY_CODE=@SM_COUNTRY_CODE, 
	SM_STATE_CODE=@SM_STATE_CODE
Where

SM_CODE = @SM_CODE