CREATE OR ALTER PROCEDURE [dbo].[SP_UpdateItemCategoryMaster]
    @I_CAT_CODE INT,
    @I_CAT_NAME NVARCHAR(50),
    @I_CAT_SHORTCLOSE BIT,
    @ES_DELETE BIT
AS
BEGIN
    SET NOCOUNT OFF;
    
    UPDATE ITEM_CATEGORY_MASTER
    SET 
        I_CAT_NAME = @I_CAT_NAME,
        I_CAT_SHORTCLOSE = @I_CAT_SHORTCLOSE,
        ES_DELETE = @ES_DELETE
    WHERE I_CAT_CODE = @I_CAT_CODE;
    
    SELECT @@ROWCOUNT AS AffectedRows;
END