CREATE OR ALTER PROCEDURE [dbo].[SP_Update_MaterialInspection]
@INSM_CODE int,
@INSM_CM_CODE int,
@INSM_DATE datetime,
@INSM_NO int,
@INSM_IWM_CODE int,
@INSM_SPOM_CODE int,
@INSM_I_CODE int,
@INSM_UOM_CODE int,
@INSM_RECEIVED_QTY float,
@INSM_OK_QTY float,
@INSM_REJ_QTY float,
@INSM_SCRAP_QTY float,
@INSM_REMARK varchar(150),
@INSM_PDR_CHECK bit,
@INSM_PDR_NO varchar(50),
@INSM_TC_CHECK bit,
@INSM_TC_NO varchar(50)


AS
BEGIN
UPDATE  INSPECTION_S_MASTER
     set INSM_CM_CODE=@INSM_CM_CODE,
			 INSM_DATE=@INSM_DATE,
		INSM_NO=@INSM_NO,
			 INSM_IWM_CODE=@INSM_IWM_CODE,
			 INSM_SPOM_CODE=@INSM_SPOM_CODE,
			INSM_I_CODE=@INSM_I_CODE,
			INSM_UOM_CODE=@INSM_UOM_CODE,
			INSM_RECEIVED_QTY=@INSM_RECEIVED_QTY,
			INSM_OK_QTY=@INSM_OK_QTY,
			INSM_REJ_QTY=@INSM_REJ_QTY,
			INSM_SCRAP_QTY=@INSM_SCRAP_QTY,
			INSM_REMARK=@INSM_REMARK,
			INSM_PDR_CHECK=@INSM_PDR_CHECK,
			INSM_PDR_NO=@INSM_PDR_NO,
			INSM_TC_CHECK=@INSM_TC_CHECK,
			INSM_TC_NO=@INSM_TC_NO
			
			where 	INSM_CODE=@INSM_CODE 	
END