CREATE OR ALTER PROCEDURE [dbo].[SP_UserExists]
    @Username NVARCHAR(50)
AS
BEGIN
    SET NOCOUNT ON;

    SELECT CASE WHEN EXISTS (SELECT 1 FROM USER_MASTER WHERE UM_USERNAME = @Username) THEN 1 ELSE 0 END AS UserExists;
END