CREATE OR ALTER PROCEDURE [dbo].[SP_USER_MASTER_INSERT]

@UM_CM_ID int,
@UM_USERNAME varchar(50),
@UM_PASSWORD varchar(max),
@UM_LEVEL varchar(50),
@UM_LASTLOGIN_DATETIME datetime,
@UM_IP_ADDRESS varchar(50),
@IS_ACTIVE bit,
@UM_EMAIL_SEND bit,
@UM_LOGIN_FLAG bit,
@UM_IS_ADMIN bit,
@UM_NAME varchar(50),
@UM_EMAIL varchar(100)

AS

Insert into USER_MASTER
(
UM_CM_ID,
UM_USERNAME,
UM_PASSWORD,
UM_LEVEL,
UM_LASTLOGIN_DATETIME,
UM_IP_ADDRESS,
IS_ACTIVE,
UM_EMAIL_SEND,
UM_LOGIN_FLAG,
UM_IS_ADMIN,
UM_NAME,
UM_EMAIL
)
values
(
@UM_CM_ID,
@UM_USERNAME,
@UM_PASSWORD,
@UM_LEVEL,
@UM_LASTLOGIN_DATETIME,
@UM_IP_ADDRESS,
@IS_ACTIVE,
@UM_EMAIL_SEND,
@UM_LOGIN_FLAG,
@UM_IS_ADMIN,
@UM_NAME,
@UM_EMAIL
)