IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[AREA_MASTER]') AND type = N'U')
BEGIN
    CREATE TABLE [dbo].[AREA_MASTER] (
        [A_CODE] INT IDENTITY(-2147483648,1) NOT NULL,
        [A_U_CODE] INT NULL,
        [A_U_DATE] DATETIME NULL,
        [A_CM_COMP_ID] INT NULL,
        [A_NO] VARCHAR(10) NULL,
        [A_DESC] VARCHAR(50) NULL,
        [ES_DELETE] BIT NULL DEFAULT ((0)),
        [MODIFY] BIT NULL DEFAULT ((0)),
        CONSTRAINT PK_AREA_MASTER PRIMARY KEY ([A_CODE])
    )
END
