USE [db_a2ea4b_sunv2]
GO

-- Check USER_MASTER table structure
SELECT COLUMN_NAME, DATA_TYPE, IS_NULLABLE, CHARACTER_MAXIMUM_LENGTH
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'USER_MASTER'
ORDER BY ORDINAL_POSITION;
GO

-- Check ROLES table structure
SELECT COLUMN_NAME, DATA_TYPE, IS_NULLABLE, CHARACTER_MAXIMUM_LENGTH
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'Roles'
ORDER BY ORDINAL_POSITION;
GO

-- Check UserRoles table structure
SELECT COLUMN_NAME, DATA_TYPE, IS_NULLABLE, CHARACTER_MAXIMUM_LENGTH
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'UserRoles'
ORDER BY ORDINAL_POSITION;
GO

-- Check existing data in ROLES
SELECT * FROM ROLES;
GO

-- Check existing data in UserRoles
SELECT * FROM UserRoles;
GO

-- Check Mohan user details
SELECT * FROM USER_MASTER WHERE USER_NAME = 'Mohan';
GO
