USE [db_a2ea4b_sunv2]
GO

-- Restore the unit by setting ES_DELETE = 0
UPDATE ITEM_UNIT_MASTER 
SET ES_DELETE = 0 
WHERE I_UOM_CODE = -2147483648;

-- Verify the unit is restored
SELECT I_UOM_CODE, I_UOM_NAME, I_UOM_DESC, ES_DELETE FROM ITEM_UNIT_MASTER WHERE I_UOM_CODE = -2147483648;
GO
