CREATE OR ALTER PROCEDURE [dbo].[ERP_UpdateCustomerTypeMaster]
    @CTM_CODE INT,
    @CTM_CM_COMP_ID INT,
    @CTM_TYPE_CODE VARCHAR(50),
    @CTM_TYPE_DESC VARCHAR(150),
    @CTM_FIRST_LETTER VARCHAR(50)
AS
BEGIN
    SET NOCOUNT ON;

    UPDATE CUSTOMER_TYPE_MASTER
    SET 
        CTM_TYPE_CODE = @CTM_TYPE_CODE,
        CTM_TYPE_DESC = @CTM_TYPE_DESC,
        CTM_FIRST_LETTER = @CTM_FIRST_LETTER,
        MODIFY = 0
    WHERE 
        CTM_CODE = @CTM_CODE 
        AND CTM_CM_COMP_ID = @CTM_CM_COMP_ID
        AND ES_DELETE = 0;
END;
GO

