-- =============================================
-- Author:      AI Assistant
-- Create date: 2025-01-24
-- Description: Creates a new Tax Invoice with ALL fields
-- =============================================
CREATE or alter PROCEDURE [dbo].[ERP_CreateTaxInvoice]
    -- Basic Details
    @CompanyCode INT,
    @InvoiceNumber INT,
    @InvoiceDate DATETIME,
    @InvoiceType TINYINT = 0,
    @Type VARCHAR(20) = 'TAXINV',
    @PaymentMethodCode INT = NULL,
    @CustomerCode INT,
    @CustomerPoCode INT = NULL,
    @DateFrom DATETIME = NULL,
    @DateTo DATETIME = NULL,
    @IsSupplementary BIT = NULL,
    @Process VARCHAR(100) = NULL,
    
    -- Amount Fields
    @NetAmount FLOAT = NULL,
    @ServiceTaxPercentage FLOAT = NULL,
    @ServiceTaxAmount FLOAT = NULL,
    @BasicExcisePercentage FLOAT = NULL,
    @BasicExciseAmount FLOAT = NULL,
    @EducationCessPercentage FLOAT = NULL,
    @EducationCessAmount FLOAT = NULL,
    @HigherEducationCessPercentage FLOAT = NULL,
    @HigherEducationCessAmount FLOAT = NULL,
    @DiscountPercentage FLOAT = NULL,
    @DiscountAmount FLOAT = NULL,
    @PackingAmount FLOAT = NULL,
    @PackingDescription VARCHAR(500) = NULL,
    @TaxCode INT = NULL,
    @TaxAmount FLOAT = NULL,
    @GrossAmount FLOAT = NULL,
    @GrossAmortizationAmount FLOAT = NULL,
    @TcsPercentage FLOAT = NULL,
    @TcsAmount FLOAT = NULL,
    
    -- Transport & Logistics
    @FreightCharges FLOAT = NULL,
    @VehicleNumber VARCHAR(50) = NULL,
    @TransportName VARCHAR(200) = NULL,
    @IssueDate DATETIME = NULL,
    @RemovalDate DATETIME = NULL,
    @StorageLocation VARCHAR(100) = NULL,
    @Remarks VARCHAR(500) = NULL,
    @CreditDays INT = NULL,
    @AsnNumber VARCHAR(50) = NULL,
    @NatureOfProduct VARCHAR(200) = NULL,
    @PreparedBy VARCHAR(100) = NULL,
    @ReworkFlag BIT = NULL,
    @TallyTransferFlag TINYINT = NULL,
    @TempTallyTransferFlag TINYINT = NULL,
    @TariffNumber VARCHAR(50) = NULL,
    @TariffName VARCHAR(200) = NULL,
    @TallyTransferFlag1 TINYINT = NULL,
    @TempTallyTransferFlag1 TINYINT = NULL,
    
    -- Additional Charges
    @TransportAmount FLOAT = NULL,
    @CourierAmount FLOAT = NULL,
    @ServicePercentage FLOAT = NULL,
    @ServiceAmount FLOAT = NULL,
    @ServiceEducationCessPercentage FLOAT = NULL,
    @ServiceEducationCessAmount FLOAT = NULL,
    @ServiceHigherEducationCessPercentage FLOAT = NULL,
    @ServiceHigherEducationCessAmount FLOAT = NULL,
    @DeliveryAddress VARCHAR(500) = NULL,
    @AlternateCustomerCode INT = NULL,
    @OtherAmount FLOAT = NULL,
    @LrNumber VARCHAR(50) = NULL,
    @LrDate DATETIME = NULL,
    @BuyerName VARCHAR(200) = NULL,
    @BuyerAddress VARCHAR(500) = NULL,
    @InsuranceAmount FLOAT = NULL,
    
    -- Export Fields
    @FinalDestination VARCHAR(200) = NULL,
    @PreCarriage VARCHAR(200) = NULL,
    @PortOfLoading VARCHAR(200) = NULL,
    @PortOfDischarge VARCHAR(200) = NULL,
    @PlaceOfDelivery VARCHAR(200) = NULL,
    @CurrencyCode INT = NULL,
    @Clearance VARCHAR(100) = NULL,
    @FlightNumber VARCHAR(50) = NULL,
    @ManufacturingDate DATETIME = NULL,
    @ExpiryDate DATETIME = NULL,
    @CurrencyRate FLOAT = NULL,
    @AuthorizedSignatory VARCHAR(200) = NULL,
    @AreaFormNumber VARCHAR(50) = NULL,
    @FormDate DATETIME = NULL,
    @Shipment VARCHAR(100) = NULL,
    @CenvatAccountNumber VARCHAR(50) = NULL,
    @BondNumber VARCHAR(50) = NULL,
    @BondDate DATETIME = NULL,
    @Ut1FileNumber VARCHAR(50) = NULL,
    @FileNumber VARCHAR(50) = NULL,
    @ExportFlag BIT = NULL,
    @ValidityDate DATETIME = NULL,
    @ExaminationBoxes VARCHAR(100) = NULL,
    @TermsOfDelivery VARCHAR(200) = NULL,
    @TermsOfPayment VARCHAR(200) = NULL,
    @VoyageNumber VARCHAR(50) = NULL,
    @PlaceOfReceipt VARCHAR(200) = NULL,
    @MarksAndNumbers VARCHAR(500) = NULL,
    @NumberOfPackages VARCHAR(50) = NULL,
    @UnNumber VARCHAR(50) = NULL,
    @HazardClass VARCHAR(50) = NULL,
    @HsCodeNumber VARCHAR(50) = NULL,
    @ContainerNumber VARCHAR(50) = NULL,
    @SealNumber VARCHAR(50) = NULL,
    @OtsNumber VARCHAR(50) = NULL,
    @CountryOfOrigin INT = NULL,
    @CountryOfDestination INT = NULL,
    @TransportBy VARCHAR(100) = NULL,
    @AreaRemarks VARCHAR(500) = NULL,
    @CarrierName VARCHAR(200) = NULL,
    @CarrierBookingNumber VARCHAR(50) = NULL,
    @ShipName VARCHAR(200) = NULL,
    @TechnicalName VARCHAR(200) = NULL,
    @OuterPackaging VARCHAR(200) = NULL,
    @InnerPackaging VARCHAR(200) = NULL,
    @SubsidiaryClass VARCHAR(50) = NULL,
    @UnPackingGroup VARCHAR(50) = NULL,
    @UnPackingCode VARCHAR(50) = NULL,
    @EmsNumber VARCHAR(50) = NULL,
    @FlashPoint VARCHAR(50) = NULL,
    @MarinePollutant BIT = NULL,
    @ShipperDeclaration VARCHAR(500) = NULL,
    @IecNumber VARCHAR(50) = NULL,
    @IecDate DATETIME = NULL,
    @CentralExciseRegistration VARCHAR(100) = NULL,
    @DateOfExamination DATETIME = NULL,
    @SuperintendentExciseName VARCHAR(200) = NULL,
    @InspectorExciseName VARCHAR(200) = NULL,
    @CustomsSealNumber VARCHAR(50) = NULL,
    @PermitENumber VARCHAR(50) = NULL,
    @IsTallyTransferred BIT = NULL,
    @NonCargoNumberOfPackages VARCHAR(50) = NULL,
    @ShippingBillNumber VARCHAR(50) = NULL,
    @AccessibleAmount FLOAT = NULL,
    @TaxableAmount FLOAT = NULL,
    @RoundingAmount FLOAT = NULL,
    @AdvanceDuty FLOAT = NULL,
    @OctriAmount FLOAT = NULL,
    @IsSuppliment BIT = NULL,
    @IssueTime VARCHAR(20) = NULL,
    @RemovalTime VARCHAR(20) = NULL,
    @LcNumber VARCHAR(50) = NULL,
    @LcDate DATETIME = NULL,
    @TransportOwner VARCHAR(200) = NULL,
    @TransportAddress VARCHAR(500) = NULL,
    @TNumber VARCHAR(50) = NULL,
    @TrayCode INT = NULL,
    @TrayQuantity FLOAT = NULL,
    @Address VARCHAR(500) = NULL,
    @StateCode INT = NULL,
    @HsnCode VARCHAR(50) = NULL,
    @ElectronicReferenceNumber VARCHAR(100) = NULL,
    @TermsAndConditions VARCHAR(MAX) = NULL,
    @AuthorizedName VARCHAR(200) = NULL,
    @AddressSelected INT = NULL,
    @ParentInvoiceCode INT = NULL,

    -- Output Parameter
    @NewInvoiceCode BIGINT OUTPUT
AS
BEGIN
    SET NOCOUNT ON;

    BEGIN TRY
        -- Insert into INVOICE_MASTER
        INSERT INTO INVOICE_MASTER (
            INM_CM_CODE, INM_NO, INM_DATE, INM_INVOICE_TYPE, INM_TYPE,
            INM_PMM_CODE, INM_P_CODE, INM_CPOM_CODE, INM_DF_DATE, INM_DT_DATE,
            INM_SUPPLEMENTORY, INM_PROCESS, INM_NET_AMT, INM_S_TAX, INM_S_TAX_AMT,
            INM_BEXCISE, INM_BE_AMT, INM_EDUC_CESS, INM_EDUC_AMT, INM_H_EDUC_CESS,
            INM_H_EDUC_AMT, INM_DISC, INM_DISC_AMT, INM_PACK_AMT, INM_PACK_DCES,
            INM_T_CODE, INM_T_AMT, INM_G_AMT, INM_G_AMORT_AMT, INM_TAX_TCS,
            INM_TAX_TCS_AMT, INM_FREIGHT, INM_VEH_NO, INM_TRANSPORT, INM_ISSUE_DATE,
            INM_REMOVAL_DATE, INM_STO_LOC, INM_REMARK, INM_C_DAYS, INM_ASN_NO,
            INM_NATURE_PRO, INM_PREPARE_BY, INM_REWORK_FLAG, INM_TALLYTNF, INM_TEMP_TALLYTNF,
            INM_TRIFF_NO, INM_TRIFF_NAME, INM_TALLYTNF1, INM_TEMP_TALLYTNF1, INM_TRANS_AMT,
            INM_COURIER_AMT, INM_SER_PER, INM_SER_AMT, INM_SER_EDUC_CESS, INM_SER_EDUC_CESS_AMT,
            INM_SER_H_EDUC_CESS, INM_SER_H_EDUC_CESS_AMT, INM_DEL_ADD, INM_P_CODE_ALT, INM_OTHER_AMT,
            INM_LR_NO, INM_LR_DATE, INM_BUYER_NAME, INM_BUYTER_ADD, INM_INSURANCE,
            INM_FINAL_DEST, INM_PRE_CARRIAGE, INM_PORT_OF_LOAD, INM_PORT_OF_DISCH, INM_PLACE_OF_DEL,
            INM_CURR_CODE, INM_CLEARANCE, INM_FLIGHT_NO, INM_MFG_DATE, INM_EXP_DATE,
            INM_CURR_RATE, INM_AUTHO_SIGN, INM_AREA_FORM_NO, INM_FORM_DATE, INM_SHIPMENT,
            INM_CENVAT_AC_NO, INM_BOND_NO, INM_BOND_DATE, INM_UT1_FILE_NO, INM_FILE_NO,
            INM_EXPORT_FLAG, INM_VALID_DATE, INM_EXA_BOXES, INM_TOD, INM_TOP,
            INM_VOY_NO, INM_PLACE_REC, INM_M_NO, INM_NOS_PACK, INM_UN_NO,
            INM_HAZ, INM_HS_CODENO, INM_CONTA_NO, INM_SEAL_NO, INM_OTS_NO,
            INM_CONTRY_ORIGIN, INM_COUNTRY_DEST, INM_TRANSPORT_BY, INM_ARE_REMARK, INM_CARRIER_NAME,
            INM_CARRIER_BOOK_NO, INM_SHIP_NAME, INM_TECH_NAME, INM_OUT_PAKGS, INM_INR_PAKG,
            INM_SUB_CLASS, INM_UN_PAK_GRP, INM_UN_PAK_CODE, INM_EMS_NO, INM_FLASH_POINT,
            INM_MARINE_POLLT, INM_SHIP_DECLAR, INM_IEC_NO, INM_IEC_DATE, INM_CEN_EXC_REG,
            INM_DATE_OF_EXAM, INM_SUP_C_EXC_NAME, INM_INSP_C_EXC_NAME, INM_CUST_SEAL_NO, INM_PER_E_NO,
            INM_IS_TALLY_TRANS, INM_NONCARGO_NOPAKG, INM_SHIPP_BILL_NO, INM_ACCESSIBLE_AMT, INM_TAXABLE_AMT,
            INM_ROUNDING_AMT, INM_ADV_DUTY, INM_OCTRI_AMT, INM_IS_SUPPLIMENT, INM_ISSU_TIME,
            INM_REMOVEL_TIME, INM_LC_NO, INM_LC_DATE, INM_TRANSPORT_OWNER, INM_TRANSPORT_ADDRESS,
            INM_TNO, INM_TRAY_CODE, INM_TRAY_QTY, INM_ADDRESS, INM_STATE,
            INM_HSN_CODE, INM_ELECTRREFNUM, INM_TERMSNCONDITIONS, INM_AUTHORIZEDNAME, INM_ADDRESS_SELECTED,
            INM_PARENT_CODE,
            ES_DELETE, MODIFY
        )
        VALUES (
            @CompanyCode, @InvoiceNumber, @InvoiceDate, @InvoiceType, @Type,
            @PaymentMethodCode, @CustomerCode, @CustomerPoCode, @DateFrom, @DateTo,
            @IsSupplementary, @Process, @NetAmount, @ServiceTaxPercentage, @ServiceTaxAmount,
            @BasicExcisePercentage, @BasicExciseAmount, @EducationCessPercentage, @EducationCessAmount, @HigherEducationCessPercentage,
            @HigherEducationCessAmount, @DiscountPercentage, @DiscountAmount, @PackingAmount, @PackingDescription,
            @TaxCode, @TaxAmount, @GrossAmount, @GrossAmortizationAmount, @TcsPercentage,
            @TcsAmount, @FreightCharges, @VehicleNumber, @TransportName, @IssueDate,
            @RemovalDate, @StorageLocation, @Remarks, @CreditDays, @AsnNumber,
            @NatureOfProduct, @PreparedBy, @ReworkFlag, @TallyTransferFlag, @TempTallyTransferFlag,
            @TariffNumber, @TariffName, @TallyTransferFlag1, @TempTallyTransferFlag1, @TransportAmount,
            @CourierAmount, @ServicePercentage, @ServiceAmount, @ServiceEducationCessPercentage, @ServiceEducationCessAmount,
            @ServiceHigherEducationCessPercentage, @ServiceHigherEducationCessAmount, @DeliveryAddress, @AlternateCustomerCode, @OtherAmount,
            @LrNumber, @LrDate, @BuyerName, @BuyerAddress, @InsuranceAmount,
            @FinalDestination, @PreCarriage, @PortOfLoading, @PortOfDischarge, @PlaceOfDelivery,
            @CurrencyCode, @Clearance, @FlightNumber, @ManufacturingDate, @ExpiryDate,
            @CurrencyRate, @AuthorizedSignatory, @AreaFormNumber, @FormDate, @Shipment,
            @CenvatAccountNumber, @BondNumber, @BondDate, @Ut1FileNumber, @FileNumber,
            @ExportFlag, @ValidityDate, @ExaminationBoxes, @TermsOfDelivery, @TermsOfPayment,
            @VoyageNumber, @PlaceOfReceipt, @MarksAndNumbers, @NumberOfPackages, @UnNumber,
            @HazardClass, @HsCodeNumber, @ContainerNumber, @SealNumber, @OtsNumber,
            @CountryOfOrigin, @CountryOfDestination, @TransportBy, @AreaRemarks, @CarrierName,
            @CarrierBookingNumber, @ShipName, @TechnicalName, @OuterPackaging, @InnerPackaging,
            @SubsidiaryClass, @UnPackingGroup, @UnPackingCode, @EmsNumber, @FlashPoint,
            @MarinePollutant, @ShipperDeclaration, @IecNumber, @IecDate, @CentralExciseRegistration,
            @DateOfExamination, @SuperintendentExciseName, @InspectorExciseName, @CustomsSealNumber, @PermitENumber,
            @IsTallyTransferred, @NonCargoNumberOfPackages, @ShippingBillNumber, @AccessibleAmount, @TaxableAmount,
            @RoundingAmount, @AdvanceDuty, @OctriAmount, @IsSuppliment, @IssueTime,
            @RemovalTime, @LcNumber, @LcDate, @TransportOwner, @TransportAddress,
            @TNumber, @TrayCode, @TrayQuantity, @Address, @StateCode,
            @HsnCode, @ElectronicReferenceNumber, @TermsAndConditions, @AuthorizedName, @AddressSelected,
            @ParentInvoiceCode,
            0, 0
        );

        -- Get the newly created Invoice Code
        SET @NewInvoiceCode = SCOPE_IDENTITY();

    END TRY
    BEGIN CATCH
        DECLARE @ErrorMessage NVARCHAR(4000) = ERROR_MESSAGE();
        DECLARE @ErrorSeverity INT = ERROR_SEVERITY();
        DECLARE @ErrorState INT = ERROR_STATE();
        
        RAISERROR(@ErrorMessage, @ErrorSeverity, @ErrorState);
    END CATCH
END
GO

