-- =============================================
-- Author:      AI Assistant
-- Create date: 2025-01-24
-- Description: Updates an existing Tax Invoice (all fields)
-- =============================================
ALTER PROCEDURE [dbo].[ERP_UpdateTaxInvoice]
    @InvoiceCode INT,
    -- (Same parameters as Create, except @InvoiceNumber which doesn't change)
    @CompanyCode INT,
    @InvoiceDate DATETIME,
    @InvoiceType TINYINT = NULL,
    @Type VARCHAR(20) = NULL,
    @PaymentMethodCode INT = NULL,
    @CustomerCode INT,
    @CustomerPoCode INT = NULL,
    @DateFrom DATETIME = NULL,
    @DateTo DATETIME = NULL,
    @IsSupplementary BIT = NULL,
    @Process VARCHAR(100) = NULL,
    @NetAmount FLOAT = NULL,
    @ServiceTaxPercentage FLOAT = NULL,
    @ServiceTaxAmount FLOAT = NULL,
    @BasicExcisePercentage FLOAT = NULL,
    @BasicExciseAmount FLOAT = NULL,
    @EducationCessPercentage FLOAT = NULL,
    @EducationCessAmount FLOAT = NULL,
    @HigherEducationCessPercentage FLOAT = NULL,
    @HigherEducationCessAmount FLOAT = NULL,
    @DiscountPercentage FLOAT = NULL,
    @DiscountAmount FLOAT = NULL,
    @PackingAmount FLOAT = NULL,
    @PackingDescription VARCHAR(500) = NULL,
    @TaxCode INT = NULL,
    @TaxAmount FLOAT = NULL,
    @GrossAmount FLOAT = NULL,
    @GrossAmortizationAmount FLOAT = NULL,
    @TcsPercentage FLOAT = NULL,
    @TcsAmount FLOAT = NULL,
    @FreightCharges FLOAT = NULL,
    @VehicleNumber VARCHAR(50) = NULL,
    @TransportName VARCHAR(200) = NULL,
    @IssueDate DATETIME = NULL,
    @RemovalDate DATETIME = NULL,
    @StorageLocation VARCHAR(100) = NULL,
    @Remarks VARCHAR(500) = NULL,
    @CreditDays INT = NULL,
    @AsnNumber VARCHAR(50) = NULL,
    @NatureOfProduct VARCHAR(200) = NULL,
    @PreparedBy VARCHAR(100) = NULL,
    @ReworkFlag BIT = NULL,
    @TariffNumber VARCHAR(50) = NULL,
    @TariffName VARCHAR(200) = NULL,
    @TransportAmount FLOAT = NULL,
    @CourierAmount FLOAT = NULL,
    @ServicePercentage FLOAT = NULL,
    @ServiceAmount FLOAT = NULL,
    @ServiceEducationCessPercentage FLOAT = NULL,
    @ServiceEducationCessAmount FLOAT = NULL,
    @ServiceHigherEducationCessPercentage FLOAT = NULL,
    @ServiceHigherEducationCessAmount FLOAT = NULL,
    @DeliveryAddress VARCHAR(500) = NULL,
    @AlternateCustomerCode INT = NULL,
    @OtherAmount FLOAT = NULL,
    @LrNumber VARCHAR(50) = NULL,
    @LrDate DATETIME = NULL,
    @BuyerName VARCHAR(200) = NULL,
    @BuyerAddress VARCHAR(500) = NULL,
    @InsuranceAmount FLOAT = NULL,
    @FinalDestination VARCHAR(200) = NULL,
    @PreCarriage VARCHAR(200) = NULL,
    @PortOfLoading VARCHAR(200) = NULL,
    @PortOfDischarge VARCHAR(200) = NULL,
    @PlaceOfDelivery VARCHAR(200) = NULL,
    @CurrencyCode INT = NULL,
    @Clearance VARCHAR(100) = NULL,
    @FlightNumber VARCHAR(50) = NULL,
    @ManufacturingDate DATETIME = NULL,
    @ExpiryDate DATETIME = NULL,
    @CurrencyRate FLOAT = NULL,
    @AuthorizedSignatory VARCHAR(200) = NULL,
    @AreaFormNumber VARCHAR(50) = NULL,
    @FormDate DATETIME = NULL,
    @Shipment VARCHAR(100) = NULL,
    @CenvatAccountNumber VARCHAR(50) = NULL,
    @BondNumber VARCHAR(50) = NULL,
    @BondDate DATETIME = NULL,
    @Ut1FileNumber VARCHAR(50) = NULL,
    @FileNumber VARCHAR(50) = NULL,
    @ExportFlag BIT = NULL,
    @ValidityDate DATETIME = NULL,
    @ExaminationBoxes VARCHAR(100) = NULL,
    @TermsOfDelivery VARCHAR(200) = NULL,
    @TermsOfPayment VARCHAR(200) = NULL,
    @VoyageNumber VARCHAR(50) = NULL,
    @PlaceOfReceipt VARCHAR(200) = NULL,
    @MarksAndNumbers VARCHAR(500) = NULL,
    @NumberOfPackages VARCHAR(50) = NULL,
    @UnNumber VARCHAR(50) = NULL,
    @HazardClass VARCHAR(50) = NULL,
    @HsCodeNumber VARCHAR(50) = NULL,
    @ContainerNumber VARCHAR(50) = NULL,
    @SealNumber VARCHAR(50) = NULL,
    @OtsNumber VARCHAR(50) = NULL,
    @CountryOfOrigin INT = NULL,
    @CountryOfDestination INT = NULL,
    @TransportBy VARCHAR(100) = NULL,
    @AreaRemarks VARCHAR(500) = NULL,
    @CarrierName VARCHAR(200) = NULL,
    @CarrierBookingNumber VARCHAR(50) = NULL,
    @ShipName VARCHAR(200) = NULL,
    @TechnicalName VARCHAR(200) = NULL,
    @OuterPackaging VARCHAR(200) = NULL,
    @InnerPackaging VARCHAR(200) = NULL,
    @SubsidiaryClass VARCHAR(50) = NULL,
    @UnPackingGroup VARCHAR(50) = NULL,
    @UnPackingCode VARCHAR(50) = NULL,
    @EmsNumber VARCHAR(50) = NULL,
    @FlashPoint VARCHAR(50) = NULL,
    @MarinePollutant BIT = NULL,
    @ShipperDeclaration VARCHAR(500) = NULL,
    @IecNumber VARCHAR(50) = NULL,
    @IecDate DATETIME = NULL,
    @CentralExciseRegistration VARCHAR(100) = NULL,
    @DateOfExamination DATETIME = NULL,
    @SuperintendentExciseName VARCHAR(200) = NULL,
    @InspectorExciseName VARCHAR(200) = NULL,
    @CustomsSealNumber VARCHAR(50) = NULL,
    @PermitENumber VARCHAR(50) = NULL,
    @NonCargoNumberOfPackages VARCHAR(50) = NULL,
    @ShippingBillNumber VARCHAR(50) = NULL,
    @AccessibleAmount FLOAT = NULL,
    @TaxableAmount FLOAT = NULL,
    @RoundingAmount FLOAT = NULL,
    @AdvanceDuty FLOAT = NULL,
    @OctriAmount FLOAT = NULL,
    @IssueTime VARCHAR(20) = NULL,
    @RemovalTime VARCHAR(20) = NULL,
    @LcNumber VARCHAR(50) = NULL,
    @LcDate DATETIME = NULL,
    @TransportOwner VARCHAR(200) = NULL,
    @TransportAddress VARCHAR(500) = NULL,
    @TNumber VARCHAR(50) = NULL,
    @TrayCode INT = NULL,
    @TrayQuantity FLOAT = NULL,
    @Address VARCHAR(500) = NULL,
    @StateCode INT = NULL,
    @HsnCode VARCHAR(50) = NULL,
    @ElectronicReferenceNumber VARCHAR(100) = NULL,
    @TermsAndConditions VARCHAR(MAX) = NULL,
    @AuthorizedName VARCHAR(200) = NULL,
    @AddressSelected INT = NULL
AS
BEGIN
    SET NOCOUNT OFF;

    BEGIN TRY
        -- Reverse old stock entries (delete all stock ledger entries for this invoice)
        DELETE FROM STOCK_LEDGER
        WHERE STL_DOC_NO = @InvoiceCode 
        AND STL_DOC_TYPE = 'TAXINV';
        
        -- Update INVOICE_MASTER
        UPDATE INVOICE_MASTER
        SET 
            INM_CM_CODE = @CompanyCode,
            INM_DATE = @InvoiceDate,
            INM_INVOICE_TYPE = @InvoiceType,
            INM_TYPE = @Type,
            INM_PMM_CODE = @PaymentMethodCode,
            INM_P_CODE = @CustomerCode,
            INM_CPOM_CODE = @CustomerPoCode,
            INM_DF_DATE = @DateFrom,
            INM_DT_DATE = @DateTo,
            INM_SUPPLEMENTORY = @IsSupplementary,
            INM_PROCESS = @Process,
            INM_NET_AMT = @NetAmount,
            INM_S_TAX = @ServiceTaxPercentage,
            INM_S_TAX_AMT = @ServiceTaxAmount,
            INM_BEXCISE = @BasicExcisePercentage,
            INM_BE_AMT = @BasicExciseAmount,
            INM_EDUC_CESS = @EducationCessPercentage,
            INM_EDUC_AMT = @EducationCessAmount,
            INM_H_EDUC_CESS = @HigherEducationCessPercentage,
            INM_H_EDUC_AMT = @HigherEducationCessAmount,
            INM_DISC = @DiscountPercentage,
            INM_DISC_AMT = @DiscountAmount,
            INM_PACK_AMT = @PackingAmount,
            INM_PACK_DCES = @PackingDescription,
            INM_T_CODE = @TaxCode,
            INM_T_AMT = @TaxAmount,
            INM_G_AMT = @GrossAmount,
            INM_G_AMORT_AMT = @GrossAmortizationAmount,
            INM_TAX_TCS = @TcsPercentage,
            INM_TAX_TCS_AMT = @TcsAmount,
            INM_FREIGHT = @FreightCharges,
            INM_VEH_NO = @VehicleNumber,
            INM_TRANSPORT = @TransportName,
            INM_ISSUE_DATE = @IssueDate,
            INM_REMOVAL_DATE = @RemovalDate,
            INM_STO_LOC = @StorageLocation,
            INM_REMARK = @Remarks,
            INM_C_DAYS = @CreditDays,
            INM_ASN_NO = @AsnNumber,
            INM_NATURE_PRO = @NatureOfProduct,
            INM_PREPARE_BY = @PreparedBy,
            INM_REWORK_FLAG = @ReworkFlag,
            INM_TRIFF_NO = @TariffNumber,
            INM_TRIFF_NAME = @TariffName,
            INM_TRANS_AMT = @TransportAmount,
            INM_COURIER_AMT = @CourierAmount,
            INM_SER_PER = @ServicePercentage,
            INM_SER_AMT = @ServiceAmount,
            INM_SER_EDUC_CESS = @ServiceEducationCessPercentage,
            INM_SER_EDUC_CESS_AMT = @ServiceEducationCessAmount,
            INM_SER_H_EDUC_CESS = @ServiceHigherEducationCessPercentage,
            INM_SER_H_EDUC_CESS_AMT = @ServiceHigherEducationCessAmount,
            INM_DEL_ADD = @DeliveryAddress,
            INM_P_CODE_ALT = @AlternateCustomerCode,
            INM_OTHER_AMT = @OtherAmount,
            INM_LR_NO = @LrNumber,
            INM_LR_DATE = @LrDate,
            INM_BUYER_NAME = @BuyerName,
            INM_BUYTER_ADD = @BuyerAddress,
            INM_INSURANCE = @InsuranceAmount,
            INM_FINAL_DEST = @FinalDestination,
            INM_PRE_CARRIAGE = @PreCarriage,
            INM_PORT_OF_LOAD = @PortOfLoading,
            INM_PORT_OF_DISCH = @PortOfDischarge,
            INM_PLACE_OF_DEL = @PlaceOfDelivery,
            INM_CURR_CODE = @CurrencyCode,
            INM_CLEARANCE = @Clearance,
            INM_FLIGHT_NO = @FlightNumber,
            INM_MFG_DATE = @ManufacturingDate,
            INM_EXP_DATE = @ExpiryDate,
            INM_CURR_RATE = @CurrencyRate,
            INM_AUTHO_SIGN = @AuthorizedSignatory,
            INM_AREA_FORM_NO = @AreaFormNumber,
            INM_FORM_DATE = @FormDate,
            INM_SHIPMENT = @Shipment,
            INM_CENVAT_AC_NO = @CenvatAccountNumber,
            INM_BOND_NO = @BondNumber,
            INM_BOND_DATE = @BondDate,
            INM_UT1_FILE_NO = @Ut1FileNumber,
            INM_FILE_NO = @FileNumber,
            INM_EXPORT_FLAG = @ExportFlag,
            INM_VALID_DATE = @ValidityDate,
            INM_EXA_BOXES = @ExaminationBoxes,
            INM_TOD = @TermsOfDelivery,
            INM_TOP = @TermsOfPayment,
            INM_VOY_NO = @VoyageNumber,
            INM_PLACE_REC = @PlaceOfReceipt,
            INM_M_NO = @MarksAndNumbers,
            INM_NOS_PACK = @NumberOfPackages,
            INM_UN_NO = @UnNumber,
            INM_HAZ = @HazardClass,
            INM_HS_CODENO = @HsCodeNumber,
            INM_CONTA_NO = @ContainerNumber,
            INM_SEAL_NO = @SealNumber,
            INM_OTS_NO = @OtsNumber,
            INM_CONTRY_ORIGIN = @CountryOfOrigin,
            INM_COUNTRY_DEST = @CountryOfDestination,
            INM_TRANSPORT_BY = @TransportBy,
            INM_ARE_REMARK = @AreaRemarks,
            INM_CARRIER_NAME = @CarrierName,
            INM_CARRIER_BOOK_NO = @CarrierBookingNumber,
            INM_SHIP_NAME = @ShipName,
            INM_TECH_NAME = @TechnicalName,
            INM_OUT_PAKGS = @OuterPackaging,
            INM_INR_PAKG = @InnerPackaging,
            INM_SUB_CLASS = @SubsidiaryClass,
            INM_UN_PAK_GRP = @UnPackingGroup,
            INM_UN_PAK_CODE = @UnPackingCode,
            INM_EMS_NO = @EmsNumber,
            INM_FLASH_POINT = @FlashPoint,
            INM_MARINE_POLLT = @MarinePollutant,
            INM_SHIP_DECLAR = @ShipperDeclaration,
            INM_IEC_NO = @IecNumber,
            INM_IEC_DATE = @IecDate,
            INM_CEN_EXC_REG = @CentralExciseRegistration,
            INM_DATE_OF_EXAM = @DateOfExamination,
            INM_SUP_C_EXC_NAME = @SuperintendentExciseName,
            INM_INSP_C_EXC_NAME = @InspectorExciseName,
            INM_CUST_SEAL_NO = @CustomsSealNumber,
            INM_PER_E_NO = @PermitENumber,
            INM_NONCARGO_NOPAKG = @NonCargoNumberOfPackages,
            INM_SHIPP_BILL_NO = @ShippingBillNumber,
            INM_ACCESSIBLE_AMT = @AccessibleAmount,
            INM_TAXABLE_AMT = @TaxableAmount,
            INM_ROUNDING_AMT = @RoundingAmount,
            INM_ADV_DUTY = @AdvanceDuty,
            INM_OCTRI_AMT = @OctriAmount,
            INM_ISSU_TIME = @IssueTime,
            INM_REMOVEL_TIME = @RemovalTime,
            INM_LC_NO = @LcNumber,
            INM_LC_DATE = @LcDate,
            INM_TRANSPORT_OWNER = @TransportOwner,
            INM_TRANSPORT_ADDRESS = @TransportAddress,
            INM_TNO = @TNumber,
            INM_TRAY_CODE = @TrayCode,
            INM_TRAY_QTY = @TrayQuantity,
            INM_ADDRESS = @Address,
            INM_STATE = @StateCode,
            INM_HSN_CODE = @HsnCode,
            INM_ELECTRREFNUM = @ElectronicReferenceNumber,
            INM_TERMSNCONDITIONS = @TermsAndConditions,
            INM_AUTHORIZEDNAME = @AuthorizedName,
            INM_ADDRESS_SELECTED = @AddressSelected
        WHERE INM_CODE = @InvoiceCode AND INM_CM_CODE = @CompanyCode;

    END TRY
    BEGIN CATCH
        DECLARE @ErrorMessage NVARCHAR(4000) = ERROR_MESSAGE();
        DECLARE @ErrorSeverity INT = ERROR_SEVERITY();
        DECLARE @ErrorState INT = ERROR_STATE();
        
        RAISERROR(@ErrorMessage, @ErrorSeverity, @ErrorState);
    END CATCH
END
GO

