-- =============================================
-- Author:      AI Assistant
-- Create date: 2025-01-24
-- Description: Gets a Tax Invoice by ID with all line items
-- =============================================
CREATE PROCEDURE [dbo].[ERP_GetTaxInvoiceById]
    @InvoiceCode INT,
    @CompanyCode INT
AS
BEGIN
    SET NOCOUNT ON;

    -- Return Invoice Master
    SELECT 
        INM_CODE AS InvoiceCode,
        INM_CM_CODE AS CompanyCode,
        INM_NO AS InvoiceNumber,
        INM_DATE AS InvoiceDate,
        INM_INVOICE_TYPE AS InvoiceType,
        INM_TYPE AS Type,
        INM_PMM_CODE AS PaymentMethodCode,
        INM_P_CODE AS CustomerCode,
        P.P_NAME AS CustomerName,
        INM_CPOM_CODE AS CustomerPoCode,
        INM_DF_DATE AS DateFrom,
        INM_DT_DATE AS DateTo,
        INM_SUPPLEMENTORY AS IsSupplementary,
        INM_PROCESS AS Process,
        INM_NET_AMT AS NetAmount,
        INM_S_TAX AS ServiceTaxPercentage,
        INM_S_TAX_AMT AS ServiceTaxAmount,
        INM_BEXCISE AS BasicExcisePercentage,
        INM_BE_AMT AS BasicExciseAmount,
        INM_EDUC_CESS AS EducationCessPercentage,
        INM_EDUC_AMT AS EducationCessAmount,
        INM_H_EDUC_CESS AS HigherEducationCessPercentage,
        INM_H_EDUC_AMT AS HigherEducationCessAmount,
        INM_DISC AS DiscountPercentage,
        INM_DISC_AMT AS DiscountAmount,
        INM_PACK_AMT AS PackingAmount,
        INM_PACK_DCES AS PackingDescription,
        INM_T_CODE AS TaxCode,
        INM_T_AMT AS TaxAmount,
        INM_G_AMT AS GrossAmount,
        INM_G_AMORT_AMT AS GrossAmortizationAmount,
        INM_TAX_TCS AS TcsPercentage,
        INM_TAX_TCS_AMT AS TcsAmount,
        INM_FREIGHT AS FreightCharges,
        INM_VEH_NO AS VehicleNumber,
        INM_TRANSPORT AS TransportName,
        INM_ISSUE_DATE AS IssueDate,
        INM_REMOVAL_DATE AS RemovalDate,
        INM_STO_LOC AS StorageLocation,
        INM_REMARK AS Remarks,
        INM_C_DAYS AS CreditDays,
        INM_ASN_NO AS AsnNumber,
        INM_NATURE_PRO AS NatureOfProduct,
        INM_PREPARE_BY AS PreparedBy,
        INM_REWORK_FLAG AS ReworkFlag,
        INM_TALLYTNF AS TallyTransferFlag,
        INM_TEMP_TALLYTNF AS TempTallyTransferFlag,
        INM_TRIFF_NO AS TariffNumber,
        INM_TRIFF_NAME AS TariffName,
        INM_TALLYTNF1 AS TallyTransferFlag1,
        INM_TEMP_TALLYTNF1 AS TempTallyTransferFlag1,
        INM_TRANS_AMT AS TransportAmount,
        INM_COURIER_AMT AS CourierAmount,
        INM_SER_PER AS ServicePercentage,
        INM_SER_AMT AS ServiceAmount,
        INM_SER_EDUC_CESS AS ServiceEducationCessPercentage,
        INM_SER_EDUC_CESS_AMT AS ServiceEducationCessAmount,
        INM_SER_H_EDUC_CESS AS ServiceHigherEducationCessPercentage,
        INM_SER_H_EDUC_CESS_AMT AS ServiceHigherEducationCessAmount,
        INM_DEL_ADD AS DeliveryAddress,
        INM_P_CODE_ALT AS AlternateCustomerCode,
        INM_OTHER_AMT AS OtherAmount,
        INM_LR_NO AS LrNumber,
        INM_LR_DATE AS LrDate,
        INM_BUYER_NAME AS BuyerName,
        INM_BUYTER_ADD AS BuyerAddress,
        INM_INSURANCE AS InsuranceAmount,
        INM_FINAL_DEST AS FinalDestination,
        INM_PRE_CARRIAGE AS PreCarriage,
        INM_PORT_OF_LOAD AS PortOfLoading,
        INM_PORT_OF_DISCH AS PortOfDischarge,
        INM_PLACE_OF_DEL AS PlaceOfDelivery,
        INM_CURR_CODE AS CurrencyCode,
        INM_CLEARANCE AS Clearance,
        INM_FLIGHT_NO AS FlightNumber,
        INM_MFG_DATE AS ManufacturingDate,
        INM_EXP_DATE AS ExpiryDate,
        INM_CURR_RATE AS CurrencyRate,
        INM_AUTHO_SIGN AS AuthorizedSignatory,
        INM_AREA_FORM_NO AS AreaFormNumber,
        INM_FORM_DATE AS FormDate,
        INM_SHIPMENT AS Shipment,
        INM_CENVAT_AC_NO AS CenvatAccountNumber,
        INM_BOND_NO AS BondNumber,
        INM_BOND_DATE AS BondDate,
        INM_UT1_FILE_NO AS Ut1FileNumber,
        INM_FILE_NO AS FileNumber,
        INM_EXPORT_FLAG AS ExportFlag,
        INM_VALID_DATE AS ValidityDate,
        INM_EXA_BOXES AS ExaminationBoxes,
        INM_TOD AS TermsOfDelivery,
        INM_TOP AS TermsOfPayment,
        INM_VOY_NO AS VoyageNumber,
        INM_PLACE_REC AS PlaceOfReceipt,
        INM_M_NO AS MarksAndNumbers,
        INM_NOS_PACK AS NumberOfPackages,
        INM_UN_NO AS UnNumber,
        INM_HAZ AS HazardClass,
        INM_HS_CODENO AS HsCodeNumber,
        INM_CONTA_NO AS ContainerNumber,
        INM_SEAL_NO AS SealNumber,
        INM_OTS_NO AS OtsNumber,
        INM_CONTRY_ORIGIN AS CountryOfOrigin,
        INM_COUNTRY_DEST AS CountryOfDestination,
        INM_TRANSPORT_BY AS TransportBy,
        INM_ARE_REMARK AS AreaRemarks,
        INM_CARRIER_NAME AS CarrierName,
        INM_CARRIER_BOOK_NO AS CarrierBookingNumber,
        INM_SHIP_NAME AS ShipName,
        INM_TECH_NAME AS TechnicalName,
        INM_OUT_PAKGS AS OuterPackaging,
        INM_INR_PAKG AS InnerPackaging,
        INM_SUB_CLASS AS SubsidiaryClass,
        INM_UN_PAK_GRP AS UnPackingGroup,
        INM_UN_PAK_CODE AS UnPackingCode,
        INM_EMS_NO AS EmsNumber,
        INM_FLASH_POINT AS FlashPoint,
        INM_MARINE_POLLT AS MarinePollutant,
        INM_SHIP_DECLAR AS ShipperDeclaration,
        INM_IEC_NO AS IecNumber,
        INM_IEC_DATE AS IecDate,
        INM_CEN_EXC_REG AS CentralExciseRegistration,
        INM_DATE_OF_EXAM AS DateOfExamination,
        INM_SUP_C_EXC_NAME AS SuperintendentExciseName,
        INM_INSP_C_EXC_NAME AS InspectorExciseName,
        INM_CUST_SEAL_NO AS CustomsSealNumber,
        INM_PER_E_NO AS PermitENumber,
        INM_IS_TALLY_TRANS AS IsTallyTransferred,
        INM_NONCARGO_NOPAKG AS NonCargoNumberOfPackages,
        INM_SHIPP_BILL_NO AS ShippingBillNumber,
        INM_ACCESSIBLE_AMT AS AccessibleAmount,
        INM_TAXABLE_AMT AS TaxableAmount,
        INM_ROUNDING_AMT AS RoundingAmount,
        INM_ADV_DUTY AS AdvanceDuty,
        INM_OCTRI_AMT AS OctriAmount,
        INM_IS_SUPPLIMENT AS IsSuppliment,
        INM_ISSU_TIME AS IssueTime,
        INM_REMOVEL_TIME AS RemovalTime,
        INM_LC_NO AS LcNumber,
        INM_LC_DATE AS LcDate,
        INM_TRANSPORT_OWNER AS TransportOwner,
        INM_TRANSPORT_ADDRESS AS TransportAddress,
        INM_TNO AS TNumber,
        INM_TRAY_CODE AS TrayCode,
        INM_TRAY_QTY AS TrayQuantity,
        INM_ADDRESS AS Address,
        INM_STATE AS StateCode,
        SM.SM_NAME AS StateName,
        INM_HSN_CODE AS HsnCode,
        INM_ELECTRREFNUM AS ElectronicReferenceNumber,
        INM_TERMSNCONDITIONS AS TermsAndConditions,
        INM_AUTHORIZEDNAME AS AuthorizedName,
        INM_ADDRESS_SELECTED AS AddressSelected,
        I.ES_DELETE AS IsDeleted,
        I.MODIFY AS IsModifyLocked
    FROM INVOICE_MASTER I
    LEFT JOIN PARTY_MASTER P ON I.INM_P_CODE = P.P_CODE
    LEFT JOIN STATE_MASTER SM ON I.INM_STATE = SM.SM_CODE
    WHERE I.INM_CODE = @InvoiceCode AND I.INM_CM_CODE = @CompanyCode;

    -- Return Invoice Details
    SELECT 
        IND_INM_CODE AS InvoiceMasterCode,
        IND_I_CODE AS ItemCode,
        IM.I_CODENO AS ItemCode_Display,
        IM.I_NAME AS ItemName,
        IND_UOM_CODE AS UomCode,
        IND_CPOM_CODE AS CustomerPoCode,
        IND_INQTY AS InvoiceQuantity,
        IND_RATE AS Rate,
        IND_CON_QTY AS ConversionQuantity,
        IND_AMORT_RATE AS AmortizationRate,
        IND_NO_PACK AS NumberOfPackages,
        IND_PACK_DESC AS PackageDescription,
        IND_QTY_PACK AS QuantityPerPack,
        IND_AMT AS Amount,
        IND_DC_NO AS DeliveryChallanNumbers,
        IND_DC_DATE AS DeliveryChallanDates,
        IND_EX_NO AS ExciseNumbers,
        IND_PROCESS_CODE AS ProcessCode,
        IND_GIN_NO AS GinNumber,
        IND_GIN_DATE AS GinDate,
        IND_GIN_RCPT AS GinReceipt,
        IND_MR_CODE AS MrCode,
        IND_GIN_ACCP AS GinAcceptance,
        IND_EX_AMT AS ExciseAmount,
        IND_E_CESS_AMT AS EducationCessAmount,
        IND_SH_CESS_AMT AS SecondaryHigherEducationCessAmount,
        E_BASIC_CentralT AS CgstPercentage,
        E_EDU_CESS_State AS SgstPercentage,
        E_H_EDU_Integrated AS IgstPercentage,
        IND_SR_NO AS SerialNumber,
        IND_REMARK AS Remarks,
        IND_IWM_CODE AS ItemWarehouseCode,
        IND_ACT_WEIGHT AS ActualWeight,
        IND_SIZE AS Size,
        IND_SUBHEADING AS SubHeading,
        IND_BACHNO AS BatchNumber,
        IND_PAK_QTY AS PackingQuantity,
        IND_GROSS_WEIGHT AS GrossWeight,
        IND_NET_WEIGHT AS NetWeight,
        IND_SIZE_OF_BOX AS SizeOfBox,
        IND_NO_OF_BARRELS AS NumberOfBarrels,
        IND_NO_OF_PACK_DESC AS NumberOfPackagesDescription,
        IND_CONTAINER_NO AS ContainerNumber,
        IND_REFUNDABLE_QTY AS RefundableQuantity,
        IND_AMORTRATE AS AmortRate,
        IND_AMORTAMT AS AmortAmount,
        IND_HSN_CODE AS HsnCode,
        IND_STORE_CODE AS StoreCode,
        ID.ES_DELETE AS IsDeleted
    FROM INVOICE_DETAIL ID
    LEFT JOIN ITEM_MASTER IM ON ID.IND_I_CODE = IM.I_CODE
    WHERE ID.IND_INM_CODE = @InvoiceCode AND ID.ES_DELETE = 0
    ORDER BY ID.IND_I_CODE;

END
GO

