-- =============================================
-- Add missing columns to AUDIT_TRAIL table
-- =============================================

USE [db_a2ea4b_sunv2];
GO

PRINT 'Adding missing columns to AUDIT_TRAIL...';

-- Use existing AUDIT_ID as Id (no need to add new column)

-- Add EntityName
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'AUDIT_TRAIL' AND COLUMN_NAME = 'EntityName')
BEGIN
    ALTER TABLE AUDIT_TRAIL ADD EntityName NVARCHAR(100);
    PRINT 'Added EntityName column';
END

-- Add EntityId
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'AUDIT_TRAIL' AND COLUMN_NAME = 'EntityId')
BEGIN
    ALTER TABLE AUDIT_TRAIL ADD EntityId NVARCHAR(50);
    PRINT 'Added EntityId column';
END

-- Add Action
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'AUDIT_TRAIL' AND COLUMN_NAME = 'Action')
BEGIN
    ALTER TABLE AUDIT_TRAIL ADD [Action] NVARCHAR(50);
    PRINT 'Added Action column';
END

-- Add UserId
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'AUDIT_TRAIL' AND COLUMN_NAME = 'UserId')
BEGIN
    ALTER TABLE AUDIT_TRAIL ADD UserId NVARCHAR(50);
    PRINT 'Added UserId column';
END

-- Add UserName
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'AUDIT_TRAIL' AND COLUMN_NAME = 'UserName')
BEGIN
    ALTER TABLE AUDIT_TRAIL ADD UserName NVARCHAR(100);
    PRINT 'Added UserName column';
END

-- Add UserRole
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'AUDIT_TRAIL' AND COLUMN_NAME = 'UserRole')
BEGIN
    ALTER TABLE AUDIT_TRAIL ADD UserRole NVARCHAR(50);
    PRINT 'Added UserRole column';
END

-- Add CompanyId
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'AUDIT_TRAIL' AND COLUMN_NAME = 'CompanyId')
BEGIN
    ALTER TABLE AUDIT_TRAIL ADD CompanyId NVARCHAR(50);
    PRINT 'Added CompanyId column';
END

-- Add IpAddress (might already exist with different casing)
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'AUDIT_TRAIL' AND COLUMN_NAME = 'IpAddress')
BEGIN
    ALTER TABLE AUDIT_TRAIL ADD IpAddress NVARCHAR(50);
    PRINT 'Added IpAddress column';
END

-- Add UserAgent (might already exist with different casing)
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'AUDIT_TRAIL' AND COLUMN_NAME = 'UserAgent')
BEGIN
    ALTER TABLE AUDIT_TRAIL ADD UserAgent NVARCHAR(500);
    PRINT 'Added UserAgent column';
END

-- Add Endpoint
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'AUDIT_TRAIL' AND COLUMN_NAME = 'Endpoint')
BEGIN
    ALTER TABLE AUDIT_TRAIL ADD Endpoint NVARCHAR(200);
    PRINT 'Added Endpoint column';
END

-- Add HttpMethod
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'AUDIT_TRAIL' AND COLUMN_NAME = 'HttpMethod')
BEGIN
    ALTER TABLE AUDIT_TRAIL ADD HttpMethod NVARCHAR(10);
    PRINT 'Added HttpMethod column';
END

-- Add Description
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'AUDIT_TRAIL' AND COLUMN_NAME = 'Description')
BEGIN
    ALTER TABLE AUDIT_TRAIL ADD [Description] NVARCHAR(500);
    PRINT 'Added Description column';
END

-- Add OldValues (might need to rename or map to existing)
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'AUDIT_TRAIL' AND COLUMN_NAME = 'OldValues')
BEGIN
    ALTER TABLE AUDIT_TRAIL ADD OldValues NVARCHAR(MAX);
    PRINT 'Added OldValues column';
END

-- Add NewValues (might need to rename or map to existing)
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'AUDIT_TRAIL' AND COLUMN_NAME = 'NewValues')
BEGIN
    ALTER TABLE AUDIT_TRAIL ADD NewValues NVARCHAR(MAX);
    PRINT 'Added NewValues column';
END

-- Add Timestamp
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'AUDIT_TRAIL' AND COLUMN_NAME = 'Timestamp')
BEGIN
    ALTER TABLE AUDIT_TRAIL ADD [Timestamp] DATETIME DEFAULT GETUTCDATE();
    PRINT 'Added Timestamp column';
END

PRINT 'AUDIT_TRAIL table alteration complete!';
GO

