-- Adds INM_IS_AUTHORIZED column to INVOICE_MASTER for approval workflow.
-- Run once before deploying ERP_ApproveTaxInvoice.sql.
IF NOT EXISTS (
    SELECT 1
    FROM   INFORMATION_SCHEMA.COLUMNS
    WHERE  TABLE_NAME  = 'INVOICE_MASTER'
      AND  COLUMN_NAME = 'INM_IS_AUTHORIZED'
)
BEGIN
    ALTER TABLE INVOICE_MASTER
        ADD INM_IS_AUTHORIZED BIT NOT NULL CONSTRAINT DF_INM_IS_AUTHORIZED DEFAULT (0);
END
GO
