-- Initialize test database
CREATE DATABASE ErpBE_Test;
GO

USE ErpBE_Test;
GO

-- Create tables
CREATE TABLE [dbo].[USER_MASTER] (
    [UM_CODE] INT IDENTITY(1,1) NOT NULL,
    [UM_USERNAME] VARCHAR(50) NOT NULL,
    [UM_PASSWORD] VARCHAR(255) NOT NULL,
    [UM_NAME] VARCHAR(100) NOT NULL,
    [UM_EMAIL] VARCHAR(100) NULL,
    [UM_CM_ID] INT NOT NULL,
    [UM_LEVEL] VARCHAR(50) NOT NULL DEFAULT 'User',
    [IS_ACTIVE] BIT NOT NULL DEFAULT 1,
    [UM_IS_ADMIN] BIT NOT NULL DEFAULT 0,
    [UM_LASTLOGIN_DATETIME] DATETIME2 NULL,
    [UM_IP_ADDRESS] VARCHAR(50) NULL,
    [ES_DELETE] BIT NOT NULL DEFAULT 0,
    [MODIFY] BIT NOT NULL DEFAULT 0,
    CONSTRAINT [PK_USER_MASTER] PRIMARY KEY CLUSTERED ([UM_CODE] ASC)
);

CREATE TABLE [dbo].[ROLES] (
    [RoleId] INT IDENTITY(1,1) NOT NULL,
    [RoleName] VARCHAR(50) NOT NULL,
    [Description] VARCHAR(200) NULL,
    [IsActive] BIT NOT NULL DEFAULT 1,
    CONSTRAINT [PK_ROLES] PRIMARY KEY CLUSTERED ([RoleId] ASC)
);

CREATE TABLE [dbo].[UserRoles] (
    [UserId] INT NOT NULL,
    [RoleId] INT NOT NULL,
    [IsActive] BIT NOT NULL DEFAULT 1,
    [AssignedDate] DATETIME2 NOT NULL DEFAULT GETDATE(),
    CONSTRAINT [PK_UserRoles] PRIMARY KEY CLUSTERED ([UserId] ASC, [RoleId] ASC),
    CONSTRAINT [FK_UserRoles_USER_MASTER] FOREIGN KEY ([UserId]) REFERENCES [dbo].[USER_MASTER] ([UM_CODE]) ON DELETE CASCADE,
    CONSTRAINT [FK_UserRoles_ROLES] FOREIGN KEY ([RoleId]) REFERENCES [dbo].[ROLES] ([RoleId]) ON DELETE CASCADE
);

CREATE TABLE [dbo].[ITEM_UNIT_MASTER] (
    [I_UOM_CODE] INT IDENTITY(1,1) NOT NULL,
    [I_UOM_CM_COMP_ID] INT NOT NULL,
    [I_UOM_NAME] VARCHAR(10) NOT NULL,
    [I_UOM_DESC] VARCHAR(100) NULL,
    [ES_DELETE] BIT NOT NULL DEFAULT 0,
    [MODIFY] BIT NOT NULL DEFAULT 0,
    CONSTRAINT [PK_ITEM_UNIT_MASTER] PRIMARY KEY CLUSTERED ([I_UOM_CODE] ASC)
);

CREATE TABLE [dbo].[AUDIT_TRAIL] (
    [AUDIT_ID] INT IDENTITY(1,1) NOT NULL,
    [TABLE_NAME] NVARCHAR(100) NOT NULL,
    [RECORD_ID] INT NOT NULL,
    [ACTION_TYPE] NVARCHAR(20) NOT NULL,
    [OLD_VALUES] NVARCHAR(MAX) NULL,
    [NEW_VALUES] NVARCHAR(MAX) NULL,
    [CREATED_DATE] DATETIME2 NOT NULL DEFAULT GETDATE(),
    [CREATED_BY] NVARCHAR(100) NOT NULL,
    [MODIFIED_DATE] DATETIME2 NULL,
    [MODIFIED_BY] NVARCHAR(100) NULL,
    [IP_ADDRESS] NVARCHAR(50) NULL,
    [USER_AGENT] NVARCHAR(500) NULL,
    [SESSION_ID] NVARCHAR(255) NULL,
    CONSTRAINT [PK_AUDIT_TRAIL] PRIMARY KEY CLUSTERED ([AUDIT_ID] ASC)
);

-- Create indexes
CREATE UNIQUE NONCLUSTERED INDEX [IX_USER_MASTER_USERNAME] ON [dbo].[USER_MASTER] ([UM_USERNAME] ASC);
CREATE NONCLUSTERED INDEX [IX_USER_MASTER_EMAIL] ON [dbo].[USER_MASTER] ([UM_EMAIL] ASC);
CREATE NONCLUSTERED INDEX [IX_USER_MASTER_COMPANY] ON [dbo].[USER_MASTER] ([UM_CM_ID] ASC);
CREATE UNIQUE NONCLUSTERED INDEX [IX_ROLES_ROLENAME] ON [dbo].[ROLES] ([RoleName] ASC);
CREATE NONCLUSTERED INDEX [IX_UserRoles_UserId] ON [dbo].[UserRoles] ([UserId] ASC);
CREATE NONCLUSTERED INDEX [IX_UserRoles_RoleId] ON [dbo].[UserRoles] ([RoleId] ASC);
CREATE NONCLUSTERED INDEX [IX_ITEM_UNIT_MASTER_COMPANY] ON [dbo].[ITEM_UNIT_MASTER] ([I_UOM_CM_COMP_ID] ASC);
CREATE UNIQUE NONCLUSTERED INDEX [IX_ITEM_UNIT_MASTER_NAME_COMPANY] ON [dbo].[ITEM_UNIT_MASTER] ([I_UOM_NAME] ASC, [I_UOM_CM_COMP_ID] ASC) WHERE [ES_DELETE] = 0;
CREATE NONCLUSTERED INDEX [IX_AUDIT_TRAIL_TABLE_RECORD] ON [dbo].[AUDIT_TRAIL] ([TABLE_NAME] ASC, [RECORD_ID] ASC);
CREATE NONCLUSTERED INDEX [IX_AUDIT_TRAIL_CREATED_DATE] ON [dbo].[AUDIT_TRAIL] ([CREATED_DATE] ASC);

PRINT 'Database and tables created successfully!';
