CREATE TABLE [dbo].[AUDIT_TRAIL] (
    [AUDIT_ID] INT IDENTITY(1,1) NOT NULL,
    [TABLE_NAME] NVARCHAR(100) NOT NULL,
    [RECORD_ID] INT NOT NULL,
    [ACTION_TYPE] NVARCHAR(20) NOT NULL,
    [OLD_VALUES] NVARCHAR(MAX) NULL,
    [NEW_VALUES] NVARCHAR(MAX) NULL,
    [CREATED_DATE] DATETIME2 NOT NULL DEFAULT GETDATE(),
    [CREATED_BY] NVARCHAR(100) NOT NULL,
    [MODIFIED_DATE] DATETIME2 NULL,
    [MODIFIED_BY] NVARCHAR(100) NULL,
    [IP_ADDRESS] NVARCHAR(50) NULL,
    [USER_AGENT] NVARCHAR(500) NULL,
    [SESSION_ID] NVARCHAR(255) NULL,
    CONSTRAINT [PK_AUDIT_TRAIL] PRIMARY KEY CLUSTERED ([AUDIT_ID] ASC)
);

-- Create indexes
CREATE NONCLUSTERED INDEX [IX_AUDIT_TRAIL_TABLE_RECORD] ON [dbo].[AUDIT_TRAIL] ([TABLE_NAME] ASC, [RECORD_ID] ASC);
CREATE NONCLUSTERED INDEX [IX_AUDIT_TRAIL_CREATED_DATE] ON [dbo].[AUDIT_TRAIL] ([CREATED_DATE] ASC);
