CREATE TABLE [dbo].[ITEM_UNIT_MASTER] (
    [I_UOM_CODE] INT IDENTITY(1,1) NOT NULL,
    [I_UOM_CM_COMP_ID] INT NOT NULL,
    [I_UOM_NAME] VARCHAR(10) NOT NULL,
    [I_UOM_DESC] VARCHAR(100) NULL,
    [ES_DELETE] BIT NOT NULL DEFAULT 0,
    [MODIFY] BIT NOT NULL DEFAULT 0,
    CONSTRAINT [PK_ITEM_UNIT_MASTER] PRIMARY KEY CLUSTERED ([I_UOM_CODE] ASC)
);

-- Create indexes
CREATE NONCLUSTERED INDEX [IX_ITEM_UNIT_MASTER_COMPANY] ON [dbo].[ITEM_UNIT_MASTER] ([I_UOM_CM_COMP_ID] ASC);
CREATE UNIQUE NONCLUSTERED INDEX [IX_ITEM_UNIT_MASTER_NAME_COMPANY] ON [dbo].[ITEM_UNIT_MASTER] ([I_UOM_NAME] ASC, [I_UOM_CM_COMP_ID] ASC) WHERE [ES_DELETE] = 0;
