CREATE TABLE [dbo].[ROLES] (
    [RoleId] INT IDENTITY(1,1) NOT NULL,
    [RoleName] VARCHAR(50) NOT NULL,
    [Description] VARCHAR(200) NULL,
    [IsActive] BIT NOT NULL DEFAULT 1,
    CONSTRAINT [PK_ROLES] PRIMARY KEY CLUSTERED ([RoleId] ASC)
);

-- Create indexes
CREATE UNIQUE NONCLUSTERED INDEX [IX_ROLES_ROLENAME] ON [dbo].[ROLES] ([RoleName] ASC);
