CREATE TABLE [dbo].[USER_MASTER] (
    [UM_CODE] INT IDENTITY(1,1) NOT NULL,
    [UM_USERNAME] VARCHAR(50) NOT NULL,
    [UM_PASSWORD] VARCHAR(255) NOT NULL,
    [UM_NAME] VARCHAR(100) NOT NULL,
    [UM_EMAIL] VARCHAR(100) NULL,
    [UM_CM_ID] INT NOT NULL,
    [UM_LEVEL] VARCHAR(50) NOT NULL DEFAULT 'User',
    [IS_ACTIVE] BIT NOT NULL DEFAULT 1,
    [UM_IS_ADMIN] BIT NOT NULL DEFAULT 0,
    [UM_LASTLOGIN_DATETIME] DATETIME2 NULL,
    [UM_IP_ADDRESS] VARCHAR(50) NULL,
    [ES_DELETE] BIT NOT NULL DEFAULT 0,
    [MODIFY] BIT NOT NULL DEFAULT 0,
    CONSTRAINT [PK_USER_MASTER] PRIMARY KEY CLUSTERED ([UM_CODE] ASC)
);

-- Create indexes
CREATE UNIQUE NONCLUSTERED INDEX [IX_USER_MASTER_USERNAME] ON [dbo].[USER_MASTER] ([UM_USERNAME] ASC);
CREATE NONCLUSTERED INDEX [IX_USER_MASTER_EMAIL] ON [dbo].[USER_MASTER] ([UM_EMAIL] ASC);
CREATE NONCLUSTERED INDEX [IX_USER_MASTER_COMPANY] ON [dbo].[USER_MASTER] ([UM_CM_ID] ASC);
