-- ── Test Isolation: Truncate Transactional Tables ────────────────────────────
--
-- PURPOSE:
--   Reset all transactional tables to a clean state before a test run.
--   Run AFTER 01-reference-data.sql and 02-test-fixtures.sql, which populate
--   the master data (customers, items, UOM, company) that tests depend on.
--
-- WHEN TO RUN:
--   Before each full CI test suite run, not between individual tests.
--   Individual tests create and clean up their own data via the API.
--
-- SAFETY GUARDS:
--   1. Only deletes rows where document codes exceed the seed threshold
--      (TEST_FIXTURE_THRESHOLD = 90000). Rows with code < 90000 are seed data.
--   2. Stock ledger entries are deleted by docType prefix 'TEST_' only,
--      so live stock balances are unaffected.
--   3. Runs inside a transaction — any failure rolls everything back.
--
-- COLUMN NAMES (authoritative list):
--   CUSTPO_MASTER:              CPOM_CODE (PK), ES_DELETE
--   CUSTPO_DETAIL:              CPOD_CODE, CPOD_CPOM_CODE (FK)
--   INVOICE_MASTER:             INM_CODE (PK), INM_TYPE, ES_DELETE
--   INVOICE_DETAIL:             IND_CODE, IND_INM_CODE (FK), ES_DELETE
--   DELIVERY_CHALLAN_MASTER:    DCM_CODE (PK), ES_DELETE
--   DELIVERY_CHALLAN_DETAIL:    DCD_CODE, DCD_DCM_CODE (FK), ES_DELETE
--   STOCK_LEDGER:               STL_I_CODE, STL_DOC_NO, STL_DOC_TYPE
--
-- NOTE: This script does NOT truncate master tables (COMPANY_MASTER,
--   CUSTOMER_MASTER, ITEM_MASTER, UOM_MASTER) — those are seeded by
--   01-reference-data.sql and must survive between runs.

SET NOCOUNT ON;
SET XACT_ABORT ON;  -- auto-rollback on any error

DECLARE @TEST_THRESHOLD INT = 90000;  -- seed data lives below this code

BEGIN TRANSACTION;

-- ── Customer PO ──────────────────────────────────────────────────────────────

DELETE FROM CUSTPO_DETAIL
WHERE CPOD_CPOM_CODE IN (
    SELECT CPOM_CODE FROM CUSTPO_MASTER WHERE CPOM_CODE >= @TEST_THRESHOLD
);

DELETE FROM CUSTPO_MASTER
WHERE CPOM_CODE >= @TEST_THRESHOLD;

-- ── Tax Invoice ───────────────────────────────────────────────────────────────

DELETE FROM INVOICE_DETAIL
WHERE IND_INM_CODE IN (
    SELECT INM_CODE FROM INVOICE_MASTER
    WHERE INM_CODE >= @TEST_THRESHOLD
      AND ISNULL(INM_TYPE, '') = 'TAXINV'
);

DELETE FROM INVOICE_MASTER
WHERE INM_CODE >= @TEST_THRESHOLD
  AND ISNULL(INM_TYPE, '') = 'TAXINV';

-- ── Labour Charge Invoice (shares INVOICE_MASTER with INM_TYPE='OutJWINM') ───

DELETE FROM INVOICE_DETAIL
WHERE IND_INM_CODE IN (
    SELECT INM_CODE FROM INVOICE_MASTER
    WHERE INM_CODE >= @TEST_THRESHOLD
      AND ISNULL(INM_TYPE, '') = 'OutJWINM'
);

DELETE FROM INVOICE_MASTER
WHERE INM_CODE >= @TEST_THRESHOLD
  AND ISNULL(INM_TYPE, '') = 'OutJWINM';

-- ── Delivery Challan ──────────────────────────────────────────────────────────

DELETE FROM DELIVERY_CHALLAN_DETAIL
WHERE DCD_DCM_CODE IN (
    SELECT DCM_CODE FROM DELIVERY_CHALLAN_MASTER WHERE DCM_CODE >= @TEST_THRESHOLD
);

DELETE FROM DELIVERY_CHALLAN_MASTER
WHERE DCM_CODE >= @TEST_THRESHOLD;

-- ── Stock Ledger (test entries only — identified by docType prefix) ───────────
-- Test entries use STL_DOC_TYPE values starting with 'TEST' or document
-- numbers >= @TEST_THRESHOLD generated by tests above.
-- Only rows created by our tests are removed; live data is unaffected.

DELETE FROM STOCK_LEDGER
WHERE STL_DOC_NO >= @TEST_THRESHOLD;

COMMIT TRANSACTION;

-- Report counts for CI log
SELECT
    (SELECT COUNT(*) FROM CUSTPO_MASTER)          AS RemainingPOs,
    (SELECT COUNT(*) FROM INVOICE_MASTER
     WHERE ISNULL(INM_TYPE,'') = 'TAXINV')        AS RemainingTaxInvoices,
    (SELECT COUNT(*) FROM INVOICE_MASTER
     WHERE ISNULL(INM_TYPE,'') = 'OutJWINM')      AS RemainingLabourInvoices,
    (SELECT COUNT(*) FROM DELIVERY_CHALLAN_MASTER) AS RemainingChallans;
